### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by AstroOrbis** [rdeepak2002/reddit-place-script-2022#1]
Hey there,
Me and a few other Reddit users are working on a project like this, and we'd like to add you to our group chat. 
Please contact me at AstroOrbis#9797.
Thanks!

**Comment by GooglesXmaddness** [comment]
Discord server link - https://discord.gg/p7ne5jwC

**Comment by rdeepak2002** [comment]
Hey thanks for the invite. It says it is invalid at the moment.

**Comment by AstroOrbis** [comment]
Can you friend me on Discord so I can invite you from there?
My user is AstroOrbis#9797.

**Comment by AstroOrbis** [comment]
Can you friend me on Discord so I can invite you from there?
My user is AstroOrbis#9797.

**Comment by rdeepak2002** [comment]
Sounds good
