### ISSUE TITLE
[BUG] SSL errors on start, cannot start

### ISSUE THREAD

**Issue by boxy-boy** [rdeepak2002/reddit-place-script-2022#100]
![Screen Shot 2022-04-02 at 12 48 54 PM](https://user-images.githubusercontent.com/69577030/161398903-09a70190-8498-410e-b1da-cda3a5723904.png)

Help? I don't know any python, or how to read the tracebacks. My JSON file is configured correctly, and i have installed the requirements using pip3.

**Comment by ixi2101** [comment]
https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

**Comment by n-OlegS** [comment]
> https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

Did this, still doesnt work.
Any ideas?

**Comment by boxy-boy** [comment]
> https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

That fixed it for me. Thank you so much!

**Comment by JAKONL** [comment]
Closing as solution has been provided.
