### ISSUE TITLE
Error when running main.py

### ISSUE THREAD

**Issue by spazlet** [rdeepak2002/reddit-place-script-2022#109]
ModuleNotFoundError: No module named 'requests'
already had pip downloaded requirements, unsure of where to go from here

**Comment by BlazingFire007** [comment]
Same here ^ macOS

**Comment by Risewill23** [comment]
Try rerunning pip install -r requirements because its getting updated a lot

**Comment by spazlet** [comment]
> Try rerunning pip install -r requirements because its getting updated a lot

ran it right before running main, still same error

**Comment by ixi2101** [comment]
what is the output of 
`pip freeze | grep request`

**Comment by JasonKassies** [comment]
running "pip install -r requirements" did nothing for me BUT
"pip install -r requirements.txt" fixed it

**Comment by spazlet** [comment]
> 

I have been running "pip install -r requirements.txt" to be clear, the error is not caused when running this

**Comment by spazlet** [comment]
> what is the output of `pip freeze | grep request`

where would I be able to find this?

**Comment by esthrshi** [comment]
Run `pip3 install -r requirements.txt`

**Comment by spazlet** [comment]
> Run `pip3 install -r requirements.txt`

got "requirement already satisfied" for all packages it attempted to install

**Comment by ixi2101** [comment]
Strange, What happens if you type
`python -c "import requests"`

**Comment by BlazingFire007** [comment]
Re running `pip install -r requirements.txt` worked for me, thanks!

**Comment by spazlet** [comment]
![image](https://user-images.githubusercontent.com/90116734/161400186-bd5a04dd-08d7-4663-a455-5631d85a91d9.png)

**Comment by BlazingFire007** [comment]
@spazlet Try manually installing `requests` then re-running the pip requirements. Worked on my mac

**Comment by spazlet** [comment]
> @spazlet Try manually installing `requests` then re-running the pip requirements. Worked on my mac

how would I do this?

**Comment by ixi2101** [comment]
> > Strange, What happens if you type
> > python -c "import requests"
> > ![image](https://user-images.githubusercontent.com/90116734/161400186-bd5a04dd-08d7-4663-a455-5631d85a91d9.png)

I think I see the problem, python.exe has requests installed, but python3.exe does not.
What version is python.exe?

`python --version`

**Comment by spazlet** [comment]
![image](https://user-images.githubusercontent.com/90116734/161400334-2960f536-555a-4e85-b900-8145c598a376.png)

**Comment by ixi2101** [comment]
Does 
`python main.py` 
yield the same error as before?

**Comment by spazlet** [comment]
> Does `python main.py` yield the same error as before?

this fixed my issue, thank you
