### ISSUE TITLE
Pixels placed diagonally

### ISSUE THREAD

**Issue by Chaos-Zero** [rdeepak2002/reddit-place-script-2022#11]
I believe there is a small bug where the drawing will come out diagonally.
At line 238 in main.py both x and y (c and r) are incremented regardless of whether the images max width or height is met.

I'm thinking perhaps it should be:
```
current_r += 1

# go back to first column when reached end of a row while drawing
if current_r >= image_width:
    current_r = 0
    current_c += 1
```

**Comment by rdeepak2002** [comment]
Hello, thanks for pointing this out! I have just pushed the fix.
