### ISSUE TITLE
[BUG] unverified_place_frequency error

### ISSUE THREAD

**Issue by esthrshi** [rdeepak2002/reddit-place-script-2022#111]
# Bug Report Form

## Describe the bug

```
[02-Apr-22 22:21:37] :: [INFO] - place-script started
Traceback (most recent call last):
  File "/Users/esthershi/Documents/GitHub/reddit-place-script-2022/main.py", line 497, in <module>
    client = PlaceClient()
  File "/Users/esthershi/Documents/GitHub/reddit-place-script-2022/main.py", line 44, in __init__
    if self.json_data["unverified_place_frequency"] is not None
KeyError: 'unverified_place_frequency'
esthershi@192 reddit-place-script-2022 % 
```

## To Reproduce

Steps to trigger the bug:

Running `python3 main.py` will cause this error. 

Probably because of the latest update. No idea how to fix. I have tried adding `"unverified_place_frequency": False,` in multiple places in the config file but still issue remains. Maybe I'm adding it in the wrong place? If so the readme isn't clear on where to add it.

**Comment by natthawk** [comment]
Add
``` 
"unverified_place_frequency": "False",
```
to the beginning of your config.json

The quotation marks are necessary; this fixed it for me.

**Comment by esthrshi** [comment]
> "unverified_place_frequency": "False",

That solved it, thank you!
