### ISSUE TITLE
[BUG]json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 14 column 5 (char 375)

### ISSUE THREAD

**Issue by DWAA1660** [rdeepak2002/reddit-place-script-2022#114]
# Bug Report Form

## Checklist

- [ yes] I am using the latest version of the code.
- [ yes] I am absolutely sure I read the README in its entirety.
- [ yes] I have made sure this is not a duplicate issue.
- [yes ] I have filled out this form correctly.

## Describe the bug

json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 14 column 5 (char 375)
but theres no values there thats the end of the document

## Expected behavior

it would run

**Comment by Adenser** [comment]
For anyone looking with similar error

**MAKE SURE YOUR CONFIG FILE IS IN CORRECT FORMAT.**

Easiest way to do is:
Got to http://json.parser.online.fr/ and paste your config file.
If there will be showed a black text on the right with "Unexpected string error" That means your config file is invalid.
![image](https://user-images.githubusercontent.com/39248856/161401034-268b62f0-b01c-4a53-91a7-71245f41f4b0.png)
In this example, there is missing _**,**_ after second user with casues error.
