### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by DWAA1660** [rdeepak2002/reddit-place-script-2022#117]
So the common error "list index out of range" what coords are alowed i cant get anything working besides 1,1

**Comment by Randomblock1** [comment]
Yep, something broke again. Try the feat/canvas2.0 branch in the meantime.

**Comment by DWAA1660** [comment]
> Yep, something broke again. Try the feat/canvas2.0 branch in the meantime.

i cant seem to find that could you perhaps supply a link

**Comment by DWAA1660** [comment]
nvm i found it thank you

**Comment by DWAA1660** [comment]
but it still doesnt work

**Comment by nsk126** [comment]
whats the issue?

**Comment by DWAA1660** [comment]
nothing changed with the other branch

**Comment by rdeepak2002** [comment]
Hello, please try the latest code now.

**Comment by Plantchant** [comment]
It should work now.

**Comment by thoroc** [comment]
Closing as assumed to be fixed. Feel free to reopen if that is not the case.
