### ISSUE TITLE
Issue in main.py

### ISSUE THREAD

**Issue by branmart** [rdeepak2002/reddit-place-script-2022#126]
# Bug Report Form

## Checklist

- [X] I am using the latest version of the code.
- [X] I am absolutely sure I read the README in its entirety.
- [X] I have made sure this is not a duplicate issue.
- [X] I have filled out this form correctly.

## Describe the bug

C:\Users\branmart\Desktop\redditbot>py main.py
[02-Apr-22 15:53:15] :: [INFO] - place-script started
Traceback (most recent call last):
  File "C:\Users\branmart\Desktop\redditbot\main.py", line 560, in <module>
    client = PlaceClient()
  File "C:\Users\branmart\Desktop\redditbot\main.py", line 31, in __init__
    self.json_data = self.get_json_data()
  File "C:\Users\branmart\Desktop\redditbot\main.py", line 100, in get_json_data
    json_data = json.load(f)
  File "Z:\Python\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "Z:\Python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "Z:\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "Z:\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 32 (char 125)

## To Reproduce

Steps to trigger the bug:

1. Execute py main.py in cmd 

## Expected behavior

Placed dots for number of workers.

## Additional context

N/A

**Comment by nsk126** [comment]
This looks like an error in the `config.json` file. Please read the instructions and see if the file is written properly.

**Comment by branmart** [comment]
> This looks like an error in the `config.json` file. Please read the instructions and see if the file is written properly.

{
    "image_path": "image.jpg",
    "image_start_coords": [568, 203],
    "thread_delay": 3,
	"unverified_place_frequency": False,

    "workers": {
        "user1": {
            "password": "[hidden]!",
            "client_id": "[hidden]",
            "client_secret": "[hidden]",
            "start_coords": [0, 0]
        },
        "user2": {
            "password": "[hidden]!",
            "client_id": "[hidden]",
            "client_secret": "[hidden]",
            "start_coords": [0, 30]
        },
        "user3": {
            "password": "[hidden]!",
            "client_id": "[hidden]",
            "client_secret": "[hidden]",
            "start_coords": [12, 11]
        }
    }
}

**Comment by warrackovama** [comment]
same here couldn't find a fix

**Comment by ixi2101** [comment]
Missing quotations around False
` "unverified_place_frequency": "False",`

**Comment by nsk126** [comment]
Change `"unverified_place_frequency": False,` to `"unverified_place_frequency": false,`

**Comment by warrackovama** [comment]
"unverified_place_frequency": "false",
{
    "image_path": "image.png",
    "image_start_coords": [741, 610],
    "thread_delay": 2,

    "workers": {
        "**Secret**": {
            "password": "**Secret**",
            "client_id": "**Secret**",
            "client_secret": "**Secret**",
            "start_coords": [0, 0]
        },
        "**Secret**": {
            "password": "**Secret**",
            "client_id": "**Secret**",
            "client_secret": "**Secret**",
            "start_coords": [0, 50]
        }
    }
}
whats wrong with this

**Comment by branmart** [comment]
> Change `"unverified_place_frequency": False,` to `"unverified_place_frequency": false,`

I changed it to properly have the quotations and is still throwing the same error.

`json.config:`

```

{
    "image_path": "image.jpg",
    "image_start_coords": [568, 203],
    "thread_delay": 3,
    "unverified_place_frequency": "False",
    "workers": {
        "user1": {
            "password": "[hidden]",
            "client_id": "[hidden]",
            "client_secret": "[hidden]",
            "start_coords": [0, 0]
        },
        "user2": {
            "password": "[hidden]",
            "client_id": "[hidden]",
            "client_secret": "[hidden]",
            "start_coords": [0, 30]
        },
        "user3": {
            "password": "[hidden!",
            "client_id": "[hidden]",
            "client_secret": "[hidden]",
            "start_coords": [12, 11]
        }
    }
}

```

Output:

```
C:\Users\branmart\Desktop\redditbot>py main.py
[02-Apr-22 16:27:25] :: [INFO] - place-script started
Traceback (most recent call last):
  File "C:\Users\branmart\Desktop\redditbot\main.py", line 560, in <module>
    client = PlaceClient()
  File "C:\Users\branmart\Desktop\redditbot\main.py", line 31, in __init__
    self.json_data = self.get_json_data()
  File "C:\Users\branmart\Desktop\redditbot\main.py", line 100, in get_json_data
    json_data = json.load(f)
  File "Z:\Python\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "Z:\Python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "Z:\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "Z:\Python\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 37 (char 69)
```

**Comment by nsk126** [comment]
> "unverified_place_frequency": "false", { "image_path": "image.png", "image_start_coords": [741, 610], "thread_delay": 2,
> 
> ```
> "workers": {
>     "**Secret**": {
>         "password": "**Secret**",
>         "client_id": "**Secret**",
>         "client_secret": "**Secret**",
>         "start_coords": [0, 0]
>     },
>     "**Secret**": {
>         "password": "**Secret**",
>         "client_id": "**Secret**",
>         "client_secret": "**Secret**",
>         "start_coords": [0, 50]
>     }
> }
> ```
> 
> } whats wrong with this

Add `"unverified_place_frequency": "false",` below `"thread_delay": 2,`.

It needs to be in the first parenthesis.

**Comment by nsk126** [comment]
> 

You have to rename the file to `config.json`. Did you do that?

**Comment by branmart** [comment]
> > > Change `"unverified_place_frequency": False,` to `"unverified_place_frequency": false,`
> > 
> > 
> > I changed it to properly have the quotations and is still throwing the same error.
> > `json.config:`
> > ```
> > 
> > {
> >     "image_path": "image.jpg",
> >     "image_start_coords": [568, 203],
> > ```
> 
> You have to rename the file to `config.json`. Did you do that?

Sorry, the actual file name is config.json.  I had a typo in the previous comment (fixed) when saying the name of the file.  If it were that issue it would give this error:

```
C:\Users\branmart\Desktop\redditbot>py main.py
[02-Apr-22 16:44:02] :: [INFO] - place-script started
No config.json file found. Read the README
```

**Comment by nsk126** [comment]
Not sure what's wrong. I copy-pasted your entire `config.json` format and it worked fine for me.

can you Change `"unverified_place_frequency": "False",` to `"unverified_place_frequency": false,` and test it?

**Comment by branmart** [comment]
> Not sure what's wrong. I copy-pasted your entire `config.json` format and it worked fine for me.
> 
> can you Change `"unverified_place_frequency": "False",` to `"unverified_place_frequency": false,` and test it?

I made the changes and got the same error:

```
C:\Users\branmart\Desktop\redditbot>py main.py
[02-Apr-22 17:14:40] :: [INFO] - place-script started
Traceback (most recent call last):
  File "C:\Users\branmart\Desktop\redditbot\main.py", line 560, in <module>
    client = PlaceClient()
  File "C:\Users\branmart\Desktop\redditbot\main.py", line 31, in __init__
    self.json_data = self.get_json_data()
  File "C:\Users\branmart\Desktop\redditbot\main.py", line 100, in get_json_data
    json_data = json.load(f)
  File "Z:\Python\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "Z:\Python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "Z:\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "Z:\Python\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 37 (char 69)
```

**Comment by nsk126** [comment]
> `json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 37 (char 69)`

Tells me something wrong at the file start.


> ```
> {
>     "image_path": "image.jpg",
>     "image_start_coords": [568, 203],
>     "thread_delay": 3,
>     "unverified_place_frequency": "False",
>     "workers": {
>         "user1": {
>             "password": "[hidden]",
>             "client_id": "[hidden]",
>             "client_secret": "[hidden]",
>             "start_coords": [0, 0]
>         },
>         "user2": {
>             "password": "[hidden]",
>             "client_id": "[hidden]",
>             "client_secret": "[hidden]",
>             "start_coords": [0, 30]
>         },
>         "user3": {
>             "password": "[hidden]",
>             "client_id": "[hidden]",
>             "client_secret": "[hidden]",
>             "start_coords": [12, 11]
>         }
>     }
> }
> ```

But your code clearly has the standard JSON structure. Are you setting `"user1"`, `"user2"`, `"user3"` properly?

**Comment by branmart** [comment]
> > `json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 37 (char 69)`
> 
> Tells me something wrong at the file start.
> 
> > ```
> > {
> >     "image_path": "image.jpg",
> >     "image_start_coords": [568, 203],
> >     "thread_delay": 3,
> >     "unverified_place_frequency": "False",
> >     "workers": {
> >         "user1": {
> >             "password": "[hidden]",
> >             "client_id": "[hidden]",
> >             "client_secret": "[hidden]",
> >             "start_coords": [0, 0]
> >         },
> >         "user2": {
> >             "password": "[hidden]",
> >             "client_id": "[hidden]",
> >             "client_secret": "[hidden]",
> >             "start_coords": [0, 30]
> >         },
> >         "user3": {
> >             "password": "[hidden]",
> >             "client_id": "[hidden]",
> >             "client_secret": "[hidden]",
> >             "start_coords": [12, 11]
> >         }
> >     }
> > }
> > ```
> 
> But your code clearly has the standard JSON structure. Are you setting `"user1"`, `"user2"`, `"user3"` properly?

That text is how it is in the `config.json` file with the exception of user1-3 being real accounts, as with the hidden information.  What was odd for me is it worked in the version before this (aside from time-limit).  I've done fresh installs from the most recent version as well but I am still receiving this issue.
