### ISSUE TITLE
Kill Thread if Permanently Rate Limited

### ISSUE THREAD

**Issue by Plantchant** [rdeepak2002/reddit-place-script-2022#127]
How would I add an option to kill a thread if the time to next pixel is > 10000 seconds? Just for performance.

**Comment by ixi2101** [comment]
Good idea, we should drop accounts that have get banned

**Comment by Plantchant** [comment]
> Good idea, we should drop accounts that have get banned

I added
`                if time_until_next_draw > 10000:
                    logging.info(f"Thread #{index} :: CANCELLED")
                    exit(1)`
and it seems to work just fine

**Comment by ZorudaRinku** [comment]
I've found that changing your IP (via VPN) will often un-restrict these accounts.
Maybe good to temporarily remove them but not permanently

**Comment by Plantchant** [comment]
Added it myself.
