### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TNT599** [rdeepak2002/reddit-place-script-2022#129]
# Bug Report Form

## Checklist

- [*] I am using the latest version of the code.
- [*] I am absolutely sure I read the README in its entirety.
- [*] I have made sure this is not a duplicate issue.
- [*] I have filled out this form correctly.

## Describe the bug

New problem, no idea what happened.

## To Reproduce

Steps to trigger the bug:

Start main.py

## Expected behavior

Should start bot.

## Additional context

Image:
![Screenshot 2022-04-02 164808](https://user-images.githubusercontent.com/73024026/161401136-f549afc5-6868-462a-8be3-fdb77c88e5f0.png)

**Comment by ixi2101** [comment]
Please pull the latest changes and this should be fixed

**Comment by TupnukPiki** [comment]
> Please pull the latest changes and this should be fixed

don't think it worked for me

 any help appreciated

**Comment by TNT599** [comment]
@TupnukPiki Scroll down and the readme tells how to fix

**Comment by TupnukPiki** [comment]
oh ok thanks
