### ISSUE TITLE
[BUG] Wrong Pixel Placement on 1+ Accounts

### ISSUE THREAD

**Issue by zachdnvn** [rdeepak2002/reddit-place-script-2022#130]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

The last digit is dropped in the x coordinate resulting in misplaced pixels on accounts after the first one.

For instance an image starting at [1234, 1234] 

Bot 1 places pixel at [1234, 1234] .
Bot 2 places pixel at [123, 1234]
 
## To Reproduce

Steps to trigger the bug:

1. Add another account
2. Run bot

## Expected behavior

Alts place pixels in correct location

## Additional context

I have a feeling that it's a result of the expanded canvas.

**Comment by clockwork04** [comment]
also having this issue

**Comment by BlazingFire007** [comment]
Same here ^

Except sometimes neither correctly place the pixels? Very strange

**Comment by russianfool** [comment]
Pretty sure this is dup of #133, there's a fix for it.
