### ISSUE TITLE
[BUG] what the hell does this mean?

### ISSUE THREAD

**Issue by bananachicken** [rdeepak2002/reddit-place-script-2022#132]
here's what the command line is spitting back at me:

![ANNOYING](https://user-images.githubusercontent.com/25674184/161401190-865dfeb4-6d31-46cd-83f3-13fee9bc4249.PNG)

i'm using the latest version. it was working, albeit slowly before the update.
sorry for being awful at this stuff

(also, what does 'Move the file 'config_example.json' to config.json' mean!? rename it??)

**Comment by scorder96** [comment]
How many workers are you using? Post a screenshot of your config.json

> (also, what does 'Move the file 'config_example.json' to config.json' mean!? rename it??)
Yes. Rename it.

**Comment by rdeepak2002** [comment]
Hello, I believe your config.json file is missing a comma. Also 'Move the file 'config_example.json' to config.json' means that you should create a copy of the  config_example.json and call this new copy config.json. Then update the config.json file with your credentials.

**Comment by bananachicken** [comment]
![stupid](https://user-images.githubusercontent.com/25674184/161401707-ac1c0b57-a846-4678-be2f-f57e6b15fcec.PNG)

here's my config.json, looks fine to me...

**Comment by bananachicken** [comment]
here's the new error.

![urgh](https://user-images.githubusercontent.com/25674184/161401820-29700031-4c77-4c78-884f-59a4ea720907.PNG)

line 31 doesnt have any text other than a closing bracket..

**Comment by scorder96** [comment]
Remove the comma in line 30.

**Comment by esthrshi** [comment]
Add `"unverified_place_frequency": false,` to the beginning of the file.

**Comment by rdeepak2002** [comment]
Hello, did the above suggestions and the latest code resolve your issue?

**Comment by bananachicken** [comment]
oh oops! no they did not, it just gave me more error messages. but i updated and it works now!

now to fix that damn rate limiting...

**Comment by rdeepak2002** [comment]
Ah okay. Since the original issue is fixed I will be closing this issue.
