### ISSUE TITLE
[BUG] Places pixel at wrong location

### ISSUE THREAD

**Issue by BlazingFire007** [rdeepak2002/reddit-place-script-2022#133]
My config used 1436, 529, but it was trying to build the image at 436, 529. This is using the latest version (5a424c0)

**Comment by XanderSo156** [comment]
I am having a similar issue, though the pixels are only around 20 off to the right of where they are supposed to be.

**Comment by robiot** [comment]
![image](https://user-images.githubusercontent.com/68228472/161401902-da553f45-78c1-469a-b81f-bdd359a27e4e.png)

It is supposed to make inside of the black lines. But makes it outsite. Can confirm this is a issue.

**Comment by ry-dgel** [comment]
I believe this is coming from the following code in `main.py` starting on line 498:
```python
canvas = 0
self.pixel_x_start += current_r
self.pixel_y_start += current_c
while self.pixel_x_start > 999:
    self.pixel_x_start -= 1000
    canvas += 1
```

The value self.pixel_x_start is reduced and then never returned back to normal, while the canvas value is reset to zero. So after the first placement each subsequent one will be offset by 1000.

**Comment by BlazingFire007** [comment]
@ry-dgel That does look like the issue. But i'm not sure how to fix it as I know nothing about the src code lol

**Comment by smith558** [comment]
Still an issue. Render the script completely non-functional. @Randomblock1

**Comment by josephdong1000** [comment]
I actually think it's the current_r variable that's busted, because when i ran the code on a fresh area the bot placed pixels the correct y value but placed them on the x axis at a large and increasing interval. If it was offset by 1000 the new pixels wouldn't be located anywhere near the desired location of the image.

**Comment by russianfool** [comment]
@josephdong1000 Possible there are multiple issues. #142 pull request fixes the pixel offset when using multiple threads, but may not address every incorrect placement.

**Comment by josephdong1000** [comment]
yeah the pixels are nowhere to be found if the target location is >1000 X
