### ISSUE TITLE
I believe this needs quotes?

### ISSUE THREAD

**Issue by scorder96** [rdeepak2002/reddit-place-script-2022#134]
![image](https://user-images.githubusercontent.com/75338253/161401543-47670414-1fea-4f64-91d5-a712cbc983cb.png)

**When for me it works only like this-**

![image](https://user-images.githubusercontent.com/75338253/161401562-41ed2e66-2055-4dda-802e-5c1a0fe1216e.png)

**Comment by ixi2101** [comment]
Correct - It looks like the README is out of date.  git pull the latest changes and the quotations are in the example json
