### ISSUE TITLE
Defaults for unverified_place_frequency and image_path

### ISSUE THREAD

**Issue by robiot** [rdeepak2002/reddit-place-script-2022#135]
Instead of requiring the json to have these values, they should default to this
```json
"unverified_place_frequency": "False",
"image_path": "image.jpg"
```

**Comment by ixi2101** [comment]
This is already the case

**Comment by robiot** [comment]
No it is not. If you have a config without these values it will throw an error
```
  File "/tmp/code/reddit-place-script-2022/main.py", line 44, in __init__
    if self.json_data["unverified_place_frequency"] is not None
KeyError: 'unverified_place_frequency'
```

**Comment by ixi2101** [comment]
Oh I see, you are saying they shouldn't be needed in the config?
My bad I thought you meant they weren't being defaulted in the config

**Comment by thoroc** [comment]
We can close this issue with the latest version of the code setting default values, right?

**Comment by rdeepak2002** [comment]
Closing issue since this has been resolved in latest code.
