### ISSUE TITLE
Proxy configuration for workers

### ISSUE THREAD

**Issue by truewulfey** [rdeepak2002/reddit-place-script-2022#136]
It would be convenient if proxies could be configured to be used with accounts, to avoid detection and ridiculous rate-limit times or something.
Most preferably HTTP proxies, with or without authorization.

**Comment by Peekofwar** [comment]
My thought would've been to use a VPN client that reroutes the computer's traffic, and have groups of accounts in different VMs.

**Comment by RomainL972** [comment]
Fixed by https://github.com/rdeepak2002/reddit-place-script-2022/commit/a55020439423c40895d4cbd9c8c5add796f928bf
