### ISSUE TITLE
Multiple accounts support?

### ISSUE THREAD

**Issue by VNGamerGit** [rdeepak2002/reddit-place-script-2022#14]
I feel like I can actually use multiple accounts by launching the script on different instances of my terminal (like, having multiple terminal tabs running the script).

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
That is what multithreading does. Put the account info in a list in the .env file and  the script will automatically create a thread for each account

**Comment by EntropyValley** [comment]
Is there a chance that we can get an offset for when the threads are started so that they don't all start at the same time? It would be nice if we had a gap between when each thread tried to place a square so that all of them don't happen at the same time.

**Comment by AggelosM** [comment]
> I feel like I can actually use multiple accounts by launching the script on different instances of my terminal (like, having multiple terminal tabs running the script).

Can you please give an example of the format?

**Comment by rdeepak2002** [comment]
Hello, there is support for multiple accounts. As @rsedxcftvgyhbujnkiqwe stated, you have to modify the .env file for this. I will update the README in a few minutes to give an example of how to do this...

**Comment by rdeepak2002** [comment]
Also there is support for offsetting where each worker starts placing pixels from the input image. You could have one worker drawing the image starting from the top left while another worker draws the image from the middle. I will update the README soon to show how to do this.

**Comment by EntropyValley** [comment]
@rdeepak2002 if the ofsetting was referring to me, I was meaning temporal offsetting.  Aka where the threads will start 30 seconds after each other (or another offset value) so that you have squares being placed over time instead of all at once when the 5 minute counter expires for all threads.

**Comment by rdeepak2002** [comment]
Hello, I have updated the README regarding instructions for multiple workers: https://github.com/rdeepak2002/reddit-place-script-2022

**Comment by rdeepak2002** [comment]
@EntropyValley Oh I see. I have just pushed up that feature. You can modify the variable, "delay_between_launches_seconds", at line 275 of main.py to specify the delay between launching new threads.

**Comment by rdeepak2002** [comment]
Closing issue since it has been resolved.
