### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TotallyNotCommunist** [rdeepak2002/reddit-place-script-2022#141]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

C:\Users\XXXXX\Desktop\reddit-place-script-2022-main>python3 main.py
Traceback (most recent call last):
  File "C:\Users\XXXXX\Desktop\reddit-place-script-2022-main\main.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Titeiiko** [comment]
I had this bug. All I did to fix it was just open it in my pycharm and somehow it worked. Idk why it doesn't work when I use it via console command or IDLE.

**Comment by JAKONL** [comment]
`requests` is a module that is installed when you run the `python -m pip install -r requirements.txt` command.
