### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TotallyNotCommunist** [rdeepak2002/reddit-place-script-2022#143]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

[02-Apr-22 12:13:08] :: [INFO] - Attempting to place White (31) pixel at 1359, 524
[02-Apr-22 12:13:09] :: [INFO] - Failed placing pixel: rate limited
[02-Apr-22 12:13:09] :: [INFO] - Received new access token: 16816************
[02-Apr-22 12:13:09] :: [INFO] - Getting board
[02-Apr-22 12:13:10] :: [INFO] - Thread #0 ::
Got image:
Exception in thread Thread-2 (task):
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\Expirement\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\Expirement\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Riley\Desktop\reddit-place-script-2022-feat-canvas2.0\main.py", line 470, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "C:\Users\Riley\Desktop\reddit-place-script-2022-feat-canvas2.0\main.py", line 325, in get_unset_pixel
    target_rgb = self.pix[x, y]
IndexError: image index out of range

## To Reproduce

Steps to trigger the bug:

1. Run python main.py in directory
2. Wait
3. See Error

## Expected behavior

Places Pixel

## Additional context

None

**Comment by tshrpl** [comment]
second half of the board isnt supported yet

**Comment by JarradTait** [comment]
It's happening on the first half of the board for me as well but not on an older version of the code. Just an issue in recent versions

**Comment by JarradTait** [comment]
`            if y >= self.image_size[1]:
                num_loops += 1
                if num_loops >= 1:
                    target_rgb = self.pix[0, 0]
                    new_rgb = self.closest_color(target_rgb)
                    return self.pixel_x_start, self.pixel_y_start, new_rgb
                y = self.pixel_y_start
`
This is what I did to fix it, when the script was reaching the end of the picture without finding a bad pixel, if num_loops>1 was not catching to default to "fixing" 0,0

**Comment by TotallyNotCommunist** [comment]
> ` if y >= self.image_size[1]: num_loops += 1 if num_loops >= 1: target_rgb = self.pix[0, 0] new_rgb = self.closest_color(target_rgb) return self.pixel_x_start, self.pixel_y_start, new_rgb y = self.pixel_y_start` This is what I did to fix it, when the script was reaching the end of the picture without finding a bad pixel, if num_loops>1 was not catching to default to "fixing" 0,0

where did you end up adding this new code?

**Comment by JarradTait** [comment]
```
    def get_unset_pixel(self, boardimg, x, y):
        pix2 = boardimg.convert("RGB").load()
        num_loops = 0
        while True:
            x += 1

            if x >= self.image_size[0]:
                y += 1
                x = 0
```
line 322 (changed the code below)
```
            if y >= self.image_size[1]:
                num_loops += 1
                if num_loops >= 1:
                    target_rgb = self.pix[0, 0]
                    new_rgb = self.closest_color(target_rgb)
                    return self.pixel_x_start, self.pixel_y_start, new_rgb
                y = self.pixel_y_start
```
line 330 (changed the code above)
```

            logging.debug(f"{x+self.pixel_x_start}, {y+self.pixel_y_start}")
            logging.debug(
                f"{x}, {y}, boardimg, {self.image_size[0]}, {self.image_size[1]}"
            )
```

**Comment by Plantchant** [comment]
Using the new script should worked. I added support for the additional canvas. The images are merged.
