### ISSUE TITLE
No config.json file found

### ISSUE THREAD

**Issue by joning20** [rdeepak2002/reddit-place-script-2022#144]
here my json file:
{
    "image_path": "image.png",
    "image_start_coords": [6969, 696],
    "thread_delay": 2,
    "unverified_place_frequency": false,
    "workers": {
        "username": {
            "password": "passwordxxx",
            "client_id": "xxxxxxxx",
            "client_secret": "xxxxx",
            "start_coords": [0, 0]
        }
    }
}

**Comment by rdeepak2002** [comment]
Hello, do you have a file called "config.json" present in the root of the project folder?

**Comment by joning20** [comment]
> 

Yes

**Comment by rdeepak2002** [comment]
<img width="514" alt="Screen Shot 2022-04-02 at 6 33 55 PM" src="https://user-images.githubusercontent.com/7110480/161403515-804a57b7-50e8-400a-ab69-46cda7e6a9fc.png">

Hm well that error only appears when Python cannot find the config.json file. Maybe replace the "config.json" string with the absolute path of thee config.json file.

**Comment by joning20** [comment]
i replaced it with the path and i got SyntaxError: invalid syntax

**Comment by rdeepak2002** [comment]
Hm maybe try the following code:

```python
configFilePath = path.join(__dirname, 'config.json')

Then instead of doing "config.json" as I did in the above screenshot on lines 95 and 99, pass in the configFilePath variable.  
```

**Comment by rdeepak2002** [comment]
Actually I just pushed up this change. Let me know if it works for you now.
