### ISSUE TITLE
How do I use multiple accounts?

### ISSUE THREAD

**Issue by NoamikoT** [rdeepak2002/reddit-place-script-2022#148]
I have 2 accounts, I created the reddit app with one of them and added the other as a developer, however for some reason only one of them is painting the pixels, they both have the same client_id and client_secret

**Comment by JAKONL** [comment]
In the [application registration page](https://old.reddit.com/prefs/apps) on reddit.com did you make sure to add the second account to the list of developers?

**Comment by NoamikoT** [comment]
> In the [application registration page](https://old.reddit.com/prefs/apps) on reddit.com did you make sure to add the second account to the list of developers?
> 
> ![Screen Shot 2022-04-02 at 4 34 11 PM](https://user-images.githubusercontent.com/16417680/161404933-eb3542a8-9b5c-42c3-8550-7b33f1e26976.png)
> 
> Edit: added screen shot

Yeah I did
