### ISSUE TITLE
AttributeError: 'Logger' object has no attribute 'DEBUG'

### ISSUE THREAD

**Issue by SQL-enwiki** [rdeepak2002/reddit-place-script-2022#149]
When attempting to start the application either via start.sh - or via python main.py, I get this:

```
Traceback (most recent call last):
  File "/home/username/reddit-place-script-2022/main.py", line 554, in <module>
    const=logger.DEBUG,
AttributeError: 'Logger' object has no attribute 'DEBUG'
```

The script is up to date.

**Comment by Ferotiq** [comment]
I second this

**Comment by Risewill23** [comment]
did you rerun the pip command?

**Comment by Ferotiq** [comment]
yup

**Comment by SQL-enwiki** [comment]
> did you rerun the pip command?

Yes

**Comment by russianfool** [comment]
There's a bug introduced. 

554/555 should be:

> logging.DEBUG
> logging.INFO

instead of logger.DEBUG and logger.INFO. Expect a patch.

**Comment by ixi2101** [comment]
Latest merge broke master...
Temp fix:
`git checkout e4010de`
May have to reinstall requirements.txt

**Comment by russianfool** [comment]
Uh... Other issues exist though, like fatal and so on.

**Comment by SwapnilSoni1999** [comment]
Fatal is also there
