### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tbrechner** [rdeepak2002/reddit-place-script-2022#152]
# Bug Report Form

## Checklist

- [X] I am using the latest version of the code.
- [X] I am absolutely sure I read the README in its entirety.
- [X] I have made sure this is not a duplicate issue.
- [X] I have filled out this form correctly.

## Describe the bug

Getting this error after following the readme.
 
```
./start.sh: /usr/local/bin/pip3: /usr/local/opt/python@3.8/bin/python3.8: bad interpreter: No such file or directory
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
## Additional context

Running on macOS.

**Comment by Ferotiq** [comment]
make sure you install using `pip3 install -r requirements.txt`

**Comment by tbrechner** [comment]
I fixed it actually. My Python install was corrupted, so I just reinstalled
it, and it works now. Thanks!

**Comment by rdeepak2002** [comment]
Closing issue since it is resolved.
