### ISSUE TITLE
[BUG] seconds remaining notice is not in correct string format

### ISSUE THREAD

**Issue by Ferotiq** [rdeepak2002/reddit-place-script-2022#153]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

Replace this text with a description of the bug.

Logger outputs `('{} seconds until next pixel is drawn', 250.0)` instead of `250 seconds until next pixel is drawn`

## To Reproduce

Steps to trigger the bug:

1. Run
2. See error

## Expected behavior

Logger should output `250 seconds until next pixel is drawn`

**Comment by JAKONL** [comment]
Introduced with the change in logging system in [https://github.com/rdeepak2002/reddit-place-script-2022/pull/72](PR72)

**Comment by Ferotiq** [comment]
can you just use f strings?

**Comment by ixi2101** [comment]
#164 Fixes
