### ISSUE TITLE
[BUG] 498542430.0 seconds...

### ISSUE THREAD

**Issue by TupnukPiki** [rdeepak2002/reddit-place-script-2022#154]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

I dont see it place a pixel at all, even before the cooldown starts

## To Reproduce

Steps to trigger the bug:

1. Run the code

## Expected behavior

It should start putting pixels in

## Additional context

![image](https://user-images.githubusercontent.com/74794075/161404477-878b3875-7893-4d49-ac1d-09b264327e20.png)

**Comment by LilGanja1337** [comment]
Your account was tagged as a bot and theres nothing that he can do about it.

**Comment by Risewill23** [comment]
you needed to increased the seconds in "thread_delay" in the config

**Comment by TupnukPiki** [comment]
> Your account was tagged as a bot and theres nothing that he can do about it.

what can i do about it though?



> you needed to increased the seconds in "thread_delay" in the config

yeah tried that and it didnt work

**Comment by Ferotiq** [comment]
you can't do anything, you can't use that account anymore

**Comment by TupnukPiki** [comment]
but there are 8 accounts there, are all of them useless?

**Comment by Ferotiq** [comment]
pretty much, unless you can wait 16 years

**Comment by ZorudaRinku** [comment]
Changing your IP with a VPN frees them up pretty well. Most of the time*

**Comment by TupnukPiki** [comment]
i can. but in the meantime, with some new accounts, what can i do to avoid getting them tagged as bots

**Comment by JAKONL** [comment]
Increase the delay, ensure you do not stop and start the script in quick succession, verify the user account emails, use accounts with karma...

**Comment by JAKONL** [comment]
Closing the issue.
