### ISSUE TITLE
[BUG] NoneType not subscriptable

### ISSUE THREAD

**Issue by AtomicGerbil** [rdeepak2002/reddit-place-script-2022#157]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

Error props up, with message:

`TypeError: 'NoneType' object is not subscriptable`
`{'payload': {'errors': [{'message': 'RunSubscribePlugins: context canceled', 'path': ['subscribe']}], 'data': None}, 'id': '2', 'type': 'data'}`

## To Reproduce

Not inherently reproducible; appears to happen at random.

## Potential Fix / Additional context

An exceptional handler to be created in main.py to handle for this issue?
This can take down a thread when it happens.

Here's more information regarding the error, if you need it.
`Exception in thread Thread-9 (task):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\owner\Desktop\PlaceBot\main.py", line 486, in task
    self.get_board(self.access_tokens[index]),
  File "C:\Users\owner\Desktop\PlaceBot\main.py", line 284, in get_board
    msg = temp["payload"]["data"]["subscribe"]`

**Comment by NFKRZZ** [comment]
I too have gotten this issue

**Comment by rdeepak2002** [comment]
Hm I think there’s an issue with the request being made in the get_board() function

**Comment by AtomicGerbil** [comment]
Supposed fix proposed by user here:
https://github.com/rdeepak2002/reddit-place-script-2022/issues/180#issuecomment-1086798036

**Comment by thoroc** [comment]
Should be fixed by: https://github.com/rdeepak2002/reddit-place-script-2022/pull/250. Feel free to re submit is this isn't the case.
