### ISSUE TITLE
I am trying to make this work, but I have no idea what to put the URLs as to get the secret key.

### ISSUE THREAD

**Issue by Portal-Mage** [rdeepak2002/reddit-place-script-2022#158]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

Replace this text with a description of the bug.

## To Reproduce

Steps to trigger the bug:

## Expected behavior

Replace this text with what _should_ have happened if no bug occurred.

**Comment by rdeepak2002** [comment]
Are you referring to the URL for generating an app with https://www.reddit.com/prefs/apps ? If so, the url does not matter. You can put in anything. Just make sure you select the "script" option when creating the app.

**Comment by Portal-Mage** [comment]
> Are you referring to the URL for generating an app with https://www.reddit.com/prefs/apps ? If so, the url does not matter. You can put in anything. Just make sure you select the "script" option when creating the app.

I get an error that says
 "you should check that url"

**Comment by ixi2101** [comment]
> > Are you referring to the URL for generating an app with https://www.reddit.com/prefs/apps ? If so, the url does not matter. You can put in anything. Just make sure you select the "script" option when creating the app.
> 
> I get an error that says "you should check that url"

URL should be of form 
`https://www.something.com`

**Comment by tshrpl** [comment]
just use `https://google.com` if you're unsure

**Comment by rdeepak2002** [comment]
Hello, did the above sample urls work for you?

**Comment by Skyline-9** [comment]
Secret Key no longer used
