### ISSUE TITLE
[BUG] All accounts placing same pixel

### ISSUE THREAD

**Issue by Phyronian** [rdeepak2002/reddit-place-script-2022#160]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

Each account is trying to place the same pixel in the same spot, even though in the config file each account's "start coords" is set 2 pixels apart ([0,0], [2,0], [4,0], etc.)

## To Reproduce

Steps to trigger the bug:

1. Configure multiple accounts in the config.json file, giving each one different start coords.
2. Run the script

## Expected behavior

Each account should place its own pixel on unique parts of the map.

EDIT:
This might be related to the script not returning the second half of the canvas right now, as my selected starting coordinates are within the second canvas.

**Comment by Phyronian** [comment]
![image](https://user-images.githubusercontent.com/59706828/161404942-3b9a86f5-36d6-434f-81dc-baabaa6d46cc.png)

**Comment by Phyronian** [comment]
![image](https://user-images.githubusercontent.com/59706828/161404976-c46e1751-b9bb-4b7d-ba9e-c87a44ff862a.png)

**Comment by Phyronian** [comment]
Ok, did a little debugging
So the starting coords are correctly read originally and saved into "current_r" and "current_c".
However, when "current_r" and "current_c" are returned by self.get_unset_pixel() in line 484, they are both set to 1, regardless of what the configured start coords are.

**Comment by test2a** [comment]
@Phyronian does this mean we need to change the start coordinates of workers to say 0,1 and 0,2 so on and so forth? if so i will send a PR for the readme

**Comment by test2a** [comment]
@Phyronian in relation to the image, what does start coordinates mean? 0.0 means top left or top right or what?

**Comment by Phyronian** [comment]
@test2a I believe this is related to the coordinates for where the script was trying to draw the image, as they were outside the original 1000x1000 canvas.  When testing within the original canvas this isn't an issue.

The starting coordinates for each worker is for where in the specified image the worker should start drawing.  So for example, [0,0] will start working at the top left pixel in the image, [0,1] will start working on the pixel below the top left one, and [1,0] will start working on the pixel to the right of the top left one.

**Comment by Plantchant** [comment]
Should be fixed now with the new code. Let me know if its still an issue.

**Comment by robiot** [comment]
Plant said it should be fixed. Reopen if still a problem
