### ISSUE TITLE
SOCKS support

### ISSUE THREAD

**Issue by ixi2101** [rdeepak2002/reddit-place-script-2022#166]
I'm off to bed now but..

Debatable how much use this will be, but it should be easy to add SOCKS proxy support.
https://pypi.org/project/PySocks/
https://stackoverflow.com/questions/12601316/how-to-make-python-requests-work-via-socks-proxy

Proxies should be added to config.json I reckon

**Comment by Risewill23** [comment]
I already have the requests setup with proxies so I just need to make a config

**Comment by Higgins4k** [comment]
> I already have the requests setup with proxies so I just need to make a config

Any plans on when you'll do that if you're going too?

**Comment by Risewill23** [comment]
> > I already have the requests setup with proxies so I just need to make a config
> 
> Any plans on when you'll do that if you're going too?

Just finished it should work but I haven't did a full test on it
