### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Burble1** [rdeepak2002/reddit-place-script-2022#168]
# Bug Report
When i try to start the bat, it instantly shuts down without any errors or anything.
## Checklist

- [ X] I am using the latest version of the code.
- [X ] I am absolutely sure I read the README in its entirety.
- [X ] I have made sure this is not a duplicate issue.
- [X ] I have filled out this form correctly.

## Describe the bug
I start the BAT, it instantly shuts down again. Config and everything should be setup correctly, i have the newest version of python.
Replace this text with a description of the bug.

## To Reproduce

Steps to trigger the bug: Not sure.. I just start it?

## Expected behavior

Should stay open and display what it is doing.

**Comment by DjRicko** [comment]
Open CMD, navigate to the folder you have it in and run the bat from command line, you'll then see the error instead of the window closing immediately.

**Comment by Burble1** [comment]
Only error i could get is "python not found"... But i do indeed have python.

**Comment by JAKONL** [comment]
That likely means that wherever the python binary was installed it is not in your ENVIRONMENT PATH. If you open up command prompt and type the word `python` does it actually start python or provide you the same error as the bat?

**Comment by Burble1** [comment]
So far it seems to have fixed it, bat is now downloading dependencies.

**Comment by JAKONL** [comment]
Thanks for the update @Burble1! Good luck and happy painting!
