### ISSUE TITLE
I have a some stuff that is prob just a simple answer.

### ISSUE THREAD

**Issue by Portal-Mage** [rdeepak2002/reddit-place-script-2022#169]
-- Where is config.json?
-- What are the starting coords coords on the image or on r/place? also what do they determine?

**Comment by rdeepak2002** [comment]
Hello, config.json is a file you create. It should be a copy of the config_example.json file, but renamed to config.json.

**Comment by rdeepak2002** [comment]
The start coords represents where to start drawing from the original image. So you could have one worker drawing the top of the image downwards while another starts drawing the middle of the image downwards.

**Comment by Portal-Mage** [comment]
where do I put the coords for the r/place location?

**Comment by rdeepak2002** [comment]
Modify the "image_start_coords" variable in config.json.
