### ISSUE TITLE
Has anyone still figured out the full bitmap fetches?

### ISSUE THREAD

**Issue by EuphoricPenguin** [rdeepak2002/reddit-place-script-2022#17]
[This static link still works, as it was posted by someone else.](https://hot-potato.reddit.com/media/canvas-images/1648827785838-0-f-8Fg292Lw.png)

Of course, simply checking in the network tab of any chromium-based browser will reveal where this came from. The only problem is that the images load in completely transparent for me. Is this the case for anyone else? If not, have we figured out how these links are formatted? I know the first bit is a UNIX timestamp, and the middle bit `-0-f-` is static across all of the full image URLs. My first thought was that the ending bit was some sort of hash function on the timestamp, but I wasn't able to find anything that quite matched up. I admittedly don't have the motivation to investigate much further, but I would hope that anyone with more information would share it around. After all, it was confirmed that r/place will be sticking around until April 4th.

**Comment by rdeepak2002** [comment]
Not 100% sure, but I think this person was able to get the entire image in their get_board() method: https://github.com/DeltaNeverUsed/reddit-place-script-2022-get-board/blob/main/main.py

**Comment by EntropyValley** [comment]
If possible, we should really try to get pixel checking implemented ASAP.  It'll raise the efficiency of each bot instance by leaps and bounds if we skip over pixels that are already correct instead of writing pixels to the same color they already are and then waiting five more minutes.  I'll try to implement tomorrow if nobody else does, but that's a long time a way in the scope of r/place.

**Comment by rdeepak2002** [comment]
I'm a bit too busy to implement it, but at line 238 I call the set_pixel method which places a pixel at a certain position. You could possibly integrate the code implemented by this person to achieve that: https://github.com/rdeepak2002/reddit-place-script-2022/issues/7

**Comment by EntropyValley** [comment]
Imo there probably needs to be some part of the routine that checks the bitmap to see if the next location to place has the same color as what it needs to be and then skips it and moves on to the next pixel if it's the same color, and then repeats that until it finds one that's different and only then actually calls set_pixel.  Theoretically, this would mean that the bots would just keep looping if the current image is displayed perfectly on the board, allowing them to almost instantly respond as soon as a rando tries to overwrite one of the pixels on the board.  I'll try to implement this tomorrow, but if someone else sees this and has the knowledge and experience to do it before me, feel free to – time is very valuable in r/place and the faster we get this implemented, the easier our lives will be.

**Comment by DeltaNeverUsed** [comment]
You can just go into my fork and copy the get_board and get_unset_pixel function, you'll have to modify them, so they work with this though #7 

the get_unset_pixel returns the cords for a pixel that has yet to be set to the correct color
and the get_board function downloads the board image

**Comment by EntropyValley** [comment]
Sweet, thanks!

**Comment by rdeepak2002** [comment]
The code regarding this has now been merged. Closing issue.
