### ISSUE TITLE
[API] Reddit API Down 

### ISSUE THREAD

**Issue by JAKONL** [rdeepak2002/reddit-place-script-2022#174]
The Reddit API is currently* down. 

This results in large blocks of errors being produced by the script.

If you can reach this page the script may work for you: https://old.reddit.com/prefs/apps

If you cannot reach that page and receive a sad buried snoo then you'll have to wait for the API servers to be restored.

I have not seen any updates on the reddit status page but keep an eye open: https://www.redditstatus.com/#day

Sad Burried Snoo image:
![Screen Shot 2022-04-02 at 5 36 47 PM](https://user-images.githubusercontent.com/16417680/161406261-8f065027-ce7f-467a-9c5d-db76843322a3.png)

*at the time of writing.

**Comment by sp4ce** [comment]
I got the same, but I am wondering if it's reddit blocking IP that are botting, and it's actually not really down.

**Comment by MilkGames** [comment]
> I got the same, but I am wondering if it's reddit blocking IP that are botting, and it's actually not really down.

No. See https://www.redditstatus.com/

**Comment by Nepmia** [comment]
No it's not blocking bots IPs, I got a VPN and tried multiples country without working, also other people that don't bot can't get on the page also @MilkGames the status page doesn't show a thing

**Comment by Risewill23** [comment]
It's going back up

**Comment by Risewill23** [comment]
I can access https://www.reddit.com/prefs/apps again

**Comment by rdeepak2002** [comment]
I believe it is back up now. Feel free to close this issue.
