### ISSUE TITLE
[BUG] "Transparent" Pixels cause the script to just spam some messages, but not draw at all

### ISSUE THREAD

**Issue by WaGi-Coding** [rdeepak2002/reddit-place-script-2022#175]
# Bug Report Form

## Checklist

- [+] I am using the latest version of the code.
- [+] I am absolutely sure I read the README in its entirety.
- [-] I have made sure this is not a duplicate issue. (so many with other transparency issues)
- [+] I have filled out this form correctly.

## Describe the bug

It does not start to draw when it detects any "transparent" pixels, see:
![image](https://user-images.githubusercontent.com/38970388/161407559-b1f7cfb4-f9a6-4461-82f4-013d5d68fea9.png)

It just spams this, then nothing for some seconds, then it does the same again

## To Reproduce

1. Use 69,42,0 "transparency" pixels in your image

## Expected behavior

It working SUS

**Comment by goodboy10** [comment]
Same Issue

**Comment by thoroc** [comment]
I'm guessing this from using a PNG file? The transparency isn't handled just now. Use a JPEG until it is fixed.

**Comment by thoroc** [comment]
Should be fixed with https://github.com/rdeepak2002/reddit-place-script-2022/pull/250, feel free to reopen if that is not the case.
