### ISSUE TITLE
Found why multithreading isn't working

### ISSUE THREAD

**Issue by Randomblock1** [rdeepak2002/reddit-place-script-2022#18]
It seems like only one thread runs the first time because firstrun immediately gets set to False. It should probably be a counter that only applies the wait when it's greater than the # of threads. Or something like that.

Alternatively, you could just move the waiting logic after you send a request. It should send a request and then loop itself into waiting.

**Comment by rdeepak2002** [comment]
Thanks! I just pushed up the fix. Lmk if anything else comes up.
