### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by ItCameFr0mMars** [rdeepak2002/reddit-place-script-2022#180]
I am using a .png image with empty space, as my artwork is not a rectangle. 
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\m4rsg\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\m4rsg\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 489, in task
    index,
  File "main.py", line 329, in get_unset_pixel
    target_rgb = self.pix[x, y][:3]
TypeError: 'int' object is not subscriptable
```

I get this on all of my threads. any fix?

**Comment by jacksors** [comment]
Is your image greyscale or rgb?

**Comment by ItCameFr0mMars** [comment]
I think it is rgb, it was a png made using photopea

**Comment by robiot** [comment]
> I think it is rgb, it was a png made using photopea

Since its an png, it uses rgba instead of rgb since pngs support opacity. Use jpg util fixed.

**Comment by Balint837** [comment]
@jacksors Just as a heads up, you can fix this yourself by changing the line somewhere around 110, from this:
`im = Image.open(self.image_path)`
to this:
`im = Image.open(self.image_path).convert("RGB")`

**Comment by thoroc** [comment]
Should be fixed by: https://github.com/rdeepak2002/reddit-place-script-2022/pull/250
