### ISSUE TITLE
Feature Request: Use only username and password

### ISSUE THREAD

**Issue by cyphgithub** [rdeepak2002/reddit-place-script-2022#185]
It's definitely possible, see https://github.com/Geosearchef/placebot and see what he's doing

**Comment by rdeepak2002** [comment]
Someone can create a pull request with the login method from their code: https://github.com/Geosearchef/placebot/blob/main/src/placer.py

**Comment by rdeepak2002** [comment]
You would have to modify this part of our code:

<img width="875" alt="Screen Shot 2022-04-03 at 1 56 13 AM" src="https://user-images.githubusercontent.com/7110480/161413965-faf4834f-5b36-485e-9c1e-f5b8e96c84eb.png">
