### ISSUE TITLE
New to python, quite confused with this error

### ISSUE THREAD

**Issue by JakeJohnson1** [rdeepak2002/reddit-place-script-2022#188]
Hi yall, 

So basically when I go to run the softwear in cmd, I run into this error and I have no clue how to get around it. The file seems correct. They are as follows. 

 C:\Users\jakej\Desktop\reddit-place-script-2022-main\config.json
       ^
SyntaxError: unexpected character after line continuation character
>>>

After adding " too both ends,  I get this.

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

Anyone got any idea what I can do???

**Comment by Higgins4k** [comment]
You're running the bat right? Confused what you mean by adding " to it.

If you are running the bat make sure your json is formatted correctly. There is a link in the readme to do that

**Comment by rdeepak2002** [comment]
Try running the following code in your terminal and please provide the log output:

```bash
pip install -r requirements.txt
python main.py --debug
```

Thank you

**Comment by JakeJohnson1** [comment]
> ```shell
> pip install -r requirements.txt
> python main.py --debug
> ```

SyntaxError: invalid syntax
>>> python main.py --debug
