### ISSUE TITLE
Extreme rate limiting 

### ISSUE THREAD

**Issue by colingoodman** [rdeepak2002/reddit-place-script-2022#19]
Ran this script with a small set of accounts and started receiving responses with rate limit errors, claiming my next available time is some absurdly high number:

> received response:  {"errors":[{"message":"Ratelimited","path":["act"],"extensions":{"nextAvailablePixelTs":1648869782000}},{"message":"ratelimit hit, next available: 1648869782000","path":["act"]}],"data":null}

> received response:  {"data":{"act":{"data":[{"id":"...","data":{"nextAvailablePixelTimestamp":1.648871046e+12,"__typename":"GetUserCooldownResponseMessageData","__typename":"GetUserCooldownResponseMessageData"},"__typename":"BasicMessage","__typename":"BasicMessage"}, ...

And thus no pixels get placed, even if I restart the script. Seems like I've triggered an anti-botting measure. Does not seem necessarily related to IP as I am still able to place on another account on a different device.

An immediate thought that comes to mind might be staggering the threads by a few seconds so they aren't all hitting the API at the same exact moment.

**Comment by rdeepak2002** [comment]
Oh that's interesting. If you would like to stagger the launch time of the threads, I would suggest modifying the "delay_between_launches_seconds" variable on line 278. It defines the time between launching each thread.

**Comment by colingoodman** [comment]
@rdeepak2002 Thanks for the quick reply. I will experiment with that setting and return with what I can figure out.

**Comment by rdeepak2002** [comment]
Np. Lmk how it goes!

**Comment by AaronAyante** [comment]
I am seeing a similar thing, even starting with a 15 second stagger time.

**Comment by Plantchant** [comment]
Maybe don't use this with your main account. I tried a stagger time of 25 seconds using 10 accounts. 
9 out of the 10 accounts now have a 138502 day cooldown.

**Comment by AaronAyante** [comment]
> Maybe don't use this with your main account. I tried a stagger time of 25 seconds using 10 accounts. I also changed the check time thingy to loop every 5 minutes instead of 1 second. 9 out of the 10 accounts now have a 138502 day cooldown.

Yep, that's what I was seeing with a few alts I tested with. I wonder if there is a karma requirement?

**Comment by ImNotOnline** [comment]
> > Maybe don't use this with your main account. I tried a stagger time of 25 seconds using 10 accounts. I also changed the check time thingy to loop every 5 minutes instead of 1 second. 9 out of the 10 accounts now have a 138502 day cooldown.
> 
> Yep, that's what I was seeing with a few alts I tested with. I wonder if there is a karma requirement?

I've been able to manually place with several alts so I don't believe there is a karma requirement

> Maybe don't use this with your main account. I tried a stagger time of 25 seconds using 10 accounts. I also changed the check time thingy to loop every 5 minutes instead of 1 second. 9 out of the 10 accounts now have a 138502 day cooldown.

I wonder if getting rid of the main would solve the issue...

**Comment by DeltaNeverUsed** [comment]
So far, I've had no issues with rate limiting on my fork, i'm running with 18 accounts at the moment

**Comment by Plantchant** [comment]
> So far, I've had no issues with rate limiting on my fork, i'm running with 18 accounts at the moment

Email verified or not? None of mine were email verified so I'm thinking that might have something to do with it.

**Comment by DeltaNeverUsed** [comment]
I'd recommend you verify them, verified gets your cooldown down to 5 minutes instead of 20

**Comment by Plantchant** [comment]
> I'd recommend you verify them, verified gets your cooldown down to 5 minutes instead of 20

Okay. I'll make new ones and try verifying this time. Thx

**Comment by Randomblock1** [comment]
I have added automatic cooldown detection. The reason the cooldown seems so high is because Reddit returns milliseconds, and the script uses seconds. A simple divide by 1000 does the trick.

Also Reddit is slowing down new accounts, by like 30 minutes or so.

Anyway, try the new commit, should work nicely.
