### ISSUE TITLE
[BUG] Failed setting options from json

### ISSUE THREAD

**Issue by Nebula6** [rdeepak2002/reddit-place-script-2022#191]
- [Y] I am using the latest version of the code.
- [Y] I am absolutely sure I read the README in its entirety.
- [Y] I have made sure this is not a duplicate issue.
- [Y] I have filled out this form correctly.

## Describe the bug

my json was fine 5 hours ago but now i get this

`Failed setting options from json. Please read README and check if you have everything in correctly. If issues are still happening then create a issue`

## To Reproduce

Steps to trigger the bug:

1. download latest main branch
2. run it

## Expected behavior

should have started 2 threads

**Comment by Risewill23** [comment]
Can you send your json with the user info replace with *

**Comment by Nebula6** [comment]
ye its just 

```
{
    "image_path": "image.png",
    "image_start_coords": [*,*],
    "thread_delay": 2,
    "unverified_place_frequency": "False",
    "workers": {
        "*": {
            "password": "*",
            "client_id": "*",
            "client_secret": "*",
            "start_coords": [*,*]
        },
        "*": {
            "password": "*",
            "client_id": "*",
            "client_secret": "*",
            "start_coords": [*,*],
            "thread_delay": 2,
            "unverified_place_frequency": "False"
        }
    }
}
```

**Comment by Risewill23** [comment]
"unverified_place_frequency": "False", needs to be "unverified_place_frequency":  false,

**Comment by dbio** [comment]
I get the same error even with  `"unverified_place_frequency": false,`

**Comment by Nebula6** [comment]
ok i just changed that to false same error, i changed to it False (cus its python) and 
```
Traceback (most recent call last):
  File "d:/projects/rplace stuff/reddit-place-script-2022/main.py", line 588, in <module>
    main()
  File "D:\anaconda\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\anaconda\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\anaconda\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "d:/projects/rplace stuff/reddit-place-script-2022/main.py", line 582, in main
    client = PlaceClient()
  File "d:/projects/rplace stuff/reddit-place-script-2022/main.py", line 28, in __init__
    self.json_data = self.get_json_data()
  File "d:/projects/rplace stuff/reddit-place-script-2022/main.py", line 122, in get_json_data
    json_data = json.load(f)
  File "D:\anaconda\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\anaconda\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\anaconda\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\anaconda\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 35 (char 128)
```

**Comment by Benjamin5678** [comment]
I tried what you tried and got same exact error

**Comment by D34DC3N73R** [comment]
Also getting this same error with docker

**Comment by wastelandgunner** [comment]
Same error here.

**Comment by varun312** [comment]
Also getting the same error with just one worker account

**Comment by rdeepak2002** [comment]
This config seems to be working for me:

```json
{
    "image_path": "image.jpg",
    "image_start_coords": [123,456],
    "thread_delay": 2,
    "unverified_place_frequency": false,
    "workers": {
        "*": {
          "password": "*",
          "client_id": "*",
          "client_secret": "*",
          "start_coords": [0, 0]
        }
    }
}
```

**Comment by Plantchant** [comment]
I'm not able to replicate this error. I think someone must have edited the code wrong.

**Comment by Benjamin5678** [comment]
> This config seems to be working for me:
> 
> Edit: never mind after pulling the latest I am getting the same error...
> 
> ```json
> {
>     "image_path": "image.jpg",
>     "image_start_coords": [123,456],
>     "thread_delay": 2,
>     "unverified_place_frequency": false,
>     "workers": {
>         "*": {
>           "password": "*",
>           "client_id": "*",
>           "client_secret": "*",
>           "start_coords": [0, 0]
>         }
>     }
> }
> ```

Do you have the main.py that worked with that config?

**Comment by rdeepak2002** [comment]
Yeah something is different in one of the newer commits.

**Comment by varun312** [comment]
I'll try to revert to the last commit on local and will get back
btw nox ci is failing on latest commit (I haven't used it ever so that might be unrelated tho)

**Comment by Nebula6** [comment]
using vscodee debug mode the error is around line 45 where its looking for something for proxies, that should be made optional so it can work with or without a proxy

**Comment by Plantchant** [comment]
Whoever added the proxies made it mandatory. You can either roll-back or add
`"proxies": null`
to your config.

**Comment by wastelandgunner** [comment]
> 

Can confirm, this is the workaround.

**Comment by rdeepak2002** [comment]
Pushed fix. Made proxies optional with following code:

<img width="568" alt="Screen Shot 2022-04-03 at 2 50 43 AM" src="https://user-images.githubusercontent.com/7110480/161415494-6fea1d7b-fe77-44a4-a926-32cc13e48d46.png">
