### ISSUE TITLE
[BUG] Large amount of seconds until next pixel

### ISSUE THREAD

**Issue by XxKingsxX-Pinu** [rdeepak2002/reddit-place-script-2022#201]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

Each user says "Thread # :: 498510860.0 seconds until next pixel is drawn"

## To Reproduce

Steps to trigger the bug:

Do everything correctly, run bot.

## Expected behavior

Worked Appropriately

**Comment by Aaron-Speedy** [comment]
This is also happening to me

**Comment by Plantchant** [comment]
Those accounts have been rate-limit banned. You can try using a VPN, but there's nothing we can do from a code standpoint.

You'll just have to make more to replace them. I also recommend turning your "thread_delay" up to 7.

**Comment by XxKingsxX-Pinu** [comment]
> Those accounts have been rate-limit banned. You can try using a VPN, but there's nothing we can do from a code standpoint.
> 
> You'll just have to make more to replace them. I also recommend turning your "thread_delay" up to 7.

These were brand new accounts hadnt even been used yet

**Comment by Plantchant** [comment]
> > Those accounts have been rate-limit banned. You can try using a VPN, but there's nothing we can do from a code standpoint.
> > You'll just have to make more to replace them. I also recommend turning your "thread_delay" up to 7.
> 
> These were brand new accounts hadnt even been used yet

That may be exactly what makes it suspicious. If you are willing to, I've found that placing the very first pixel for a new account manually decreasing the rate at which they get banned since it adds the "mona lisa" app through the main site instead of api.

**Comment by XxKingsxX-Pinu** [comment]
Yep that did work, although I don't really think its worth my time anymore.
