### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'contents'

### ISSUE THREAD

**Issue by Sethycakes** [rdeepak2002/reddit-place-script-2022#212]
Hi, here's my config file:
```
{
    "image_path": "image.jpg",
    "image_start_coords": [1249, 82],
    "thread_delay": 2,
    "unverified_place_frequency": false,
    "workers": {
        "[redacted]": {
            "password": "[redacted]",
            "start_coords": [0, 0]
        }
    }
}
```

And here's the error:
```
2022-04-03 00:37:08.957 | INFO     | __main__:load_image:140 - Loaded image size: (32, 32)
2022-04-03 00:37:09.968 | INFO     | __main__:task:427 - Thread #0 ::
2022-04-03 00:37:09.970 | INFO     | __main__:task:442 - Thread #0 :: Refreshing access token
Authorization successful!
Obtaining access token...
Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\[redacted]\reddit-place-script-2022-main\main.py", line 484, in task
    .contents[0][len("window.__r = ") : -1]
AttributeError: 'NoneType' object has no attribute 'contents'
```

**Comment by Ph-ill** [comment]
Also getting this errror

`2022-04-03 10:41:19.141 | INFO     | __main__:load_image:144 - Loaded image size: (37, 12)
Authorization successful!
Obtaining access token...
Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\phill\reddit-place-script-2022\main.py", line 504, in task
    .contents[0][len("window.__r = ") : -1]
AttributeError: 'NoneType' object has no attribute 'contents'`

**Comment by Ph-ill** [comment]
Did some digging and it appears we're getting this error because line 500
`r = client.get("https://www.reddit.com/")`
is returning `<Response [429]>`

ie. [Too many requests ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429)

Gonna try with a vpn or something now and see if that remedies the issue, not sure why I'm getting it though I'm only running it with one account.

**Comment by thoroc** [comment]
Just tried something similar without success @Ph-ill ; branch not pushed

**Comment by Ph-ill** [comment]
> Just tried something similar without success @Ph-ill ; branch not pushed

By adding something like 

`client.headers.update({'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36'})`

I can get an OK 200 return from the request to https://reddit.com but that still doesn't seem to resolve the issue for some reason, still trying to figure it out now.

**Comment by imnotverygood** [comment]
I realised this error was only occuring on accounts where old reddit style is enabled. So I was able to resolve this by changing the url we are requesting to from `www.reddit.com` to `new.reddit.com`. I have also included a useragent like @Ph-ill suggested.

**Comment by Ph-ill** [comment]
> I realised this error was only occuring on accounts where old reddit style is enabled. So I was able to resolve this by changing the url we are requesting to from `www.reddit.com` to `new.reddit.com`. I have also included a useragent like @Ph-ill suggested.

Gah that seems so obvious now, give me 10 minutes and I'll put in a pull request with the changes.

**Comment by Ph-ill** [comment]
Can confirm the user-agent swap and changing `r = client.get("https://www.reddit.com/")` to `r = client.get("https://new.reddit.com/")`

resolves all the issues mentioned in this thread, I've submitted a pull request with the changes, I have the updated script running on my account that has opted out of the redesign on my pc right now with 0 issues.

**Comment by Ph-ill** [comment]
#244
