### ISSUE TITLE
Protected main branch

### ISSUE THREAD

**Issue by robiot** [rdeepak2002/reddit-place-script-2022#216]
You should be able to enable this @rdeepak2002 since you have github pro.
This will prevent direct pushes to main

**Comment by rdeepak2002** [comment]
Added

![3F1606C1-F470-4285-96E1-0C70BF64E151](https://user-images.githubusercontent.com/7110480/161422115-3b84bc3c-e276-4c56-9971-ca9fa762d837.png)

**Comment by robiot** [comment]
Perfect. Thank you!

**Comment by rdeepak2002** [comment]
Np. Thanks for the suggestion!
