### ISSUE TITLE
[BUG] Error checking current pixel

### ISSUE THREAD

**Issue by dlashlee** [rdeepak2002/reddit-place-script-2022#217]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

Overwriting pixels that are already the correct color

Appears to be reading (0, 0, 0) as the current color

## Additional context

2022-04-03 10:37:28.310 | INFO     | __main__:get_board:330 - Got image: 
2022-04-03 10:37:28.312 | DEBUG    | __main__:get_unset_pixel:352 - 1146, 510
2022-04-03 10:37:28.313 | DEBUG    | __main__:get_unset_pixel:353 - 3, 0, boardimg, 27, 30
2022-04-03 10:37:28.313 | DEBUG    | __main__:get_unset_pixel:361 - (0, 0, 0), (190, 0, 57), True, True
2022-04-03 10:37:28.313 | DEBUG    | __main__:get_unset_pixel:369 - Replacing (0, 0, 0) pixel at: 1146,510 with (190, 0, 57) color

**Comment by funwithtriangles** [comment]
Can confirm this is happening with recent changes

**Comment by Plantchant** [comment]
who keeps messing up my fix >.<

**Comment by rdeepak2002** [comment]
@Plantchant 
Lol dw I protected main now (I think) so only pull requests can be made this point onwards. This is thanks to the suggestion made by the other collaborator.

**Comment by Plantchant** [comment]
@dlashlee 
I know it's not ideal, but I'm too tired to check through code right now. Here's the last time I worked on it and I believe this problem was fixed at the time.
https://github.com/rdeepak2002/reddit-place-script-2022/tree/c312857020e586884ec7f399e743bca3ec00806d

-------
@rdeepak2002 That's probably a good idea.

**Comment by dlashlee** [comment]
I redownloaded the current and its fixed.

**Comment by funwithtriangles** [comment]
Still broken for me...

**Comment by funwithtriangles** [comment]
Re-opening as I'm seeing this often

**Comment by funwithtriangles** [comment]
It seems to be sampling from the wrong half of the board
