### ISSUE TITLE
Use squash and merge

### ISSUE THREAD

**Issue by robiot** [rdeepak2002/reddit-place-script-2022#223]
@rdeepak2002 @ixi2101 @Randomblock1 @thoroc @RomainL972 @Plantchant 

When merging a pull request, press the arrow down and choose squash and merge. This will keep the commit tree much cleaner.

**Comment by robiot** [comment]
But remember to change the name to something descriptive if it isnt already

**Comment by thoroc** [comment]
@rdeepak2002 can you change the default settings to set the merge policy to `Squash and Merge`?

**Comment by robiot** [comment]
@funwithtriangles Please also use squash and merge

**Comment by funwithtriangles** [comment]
I have been 🙃

**Comment by robiot** [comment]
> I have been upside_down_face

Oh, well sorry then. This just looked like a normal merge for me
![image](https://user-images.githubusercontent.com/68228472/161431477-99e24c28-1f9a-4d74-8cb1-0566ff5a5669.png)

**Comment by funwithtriangles** [comment]
Whoops! I think you're right. I'll keep an eye on that, I thought my button was defaulting to "Squash and merge" but maybe not

**Comment by rdeepak2002** [comment]
> @rdeepak2002 can you change the default settings to set the merge policy to `Squash and Merge`?

Hello, do you know where this is located in settings? I do not see it under the branch settings.

<img width="795" alt="Screen Shot 2022-04-03 at 12 22 55 PM" src="https://user-images.githubusercontent.com/7110480/161437700-a9d11989-2d4d-4934-b162-af2cb29ecdbf.png">

<img width="807" alt="Screen Shot 2022-04-03 at 12 23 05 PM" src="https://user-images.githubusercontent.com/7110480/161437711-d2d77c0a-d1c5-408f-bb08-8b8122629f10.png">

**Comment by rdeepak2002** [comment]
Oh never mind. Do I only allow squash merging?:

<img width="824" alt="Screen Shot 2022-04-03 at 12 24 25 PM" src="https://user-images.githubusercontent.com/7110480/161437791-4930b909-2514-487f-8d6a-0be8b323b0d9.png">

**Comment by robiot** [comment]
> Oh never mind. Do I only allow squash merging?:
> 
> <img alt="Screen Shot 2022-04-03 at 12 24 25 PM" width="824" src="https://user-images.githubusercontent.com/7110480/161437791-4930b909-2514-487f-8d6a-0be8b323b0d9.png">

Yep!

**Comment by rdeepak2002** [comment]
Cool, thanks. It is now enabled:

<img width="802" alt="Screen Shot 2022-04-03 at 12 26 21 PM" src="https://user-images.githubusercontent.com/7110480/161437861-37ffe8b1-792e-4b0d-97cc-d42d1e6fdb9a.png">
