### ISSUE TITLE
sorry i am stupid. didnt read the README. 

### ISSUE THREAD

**Issue by Memeverze** [rdeepak2002/reddit-place-script-2022#243]
# Bug Report Form

## Checklist

- [ yes ] I am using the latest version of the code.
- [ yes ] I am absolutely sure I read the README in its entirety.
- [ idk ] I have made sure this is not a duplicate issue.
- [ probably] I have filled out this form correctly.

## Describe the bug

when i start the bat file it opens fgro a split second. ive got a screenshot of it and it says requirement is satisfied on many diffrent paths and stuff. screenshot: https://imgur.com/a/0M5Fhpx

## To Reproduce

Steps to trigger the bug:

start the bat

## Expected behavior

code work

## Additional context

no

**Comment by MivianTKN** [comment]
That just means you already have the python packages it is trying to download. If it’s not working, something else is causing the issue.

**Comment by Memeverze** [comment]
but it closes after that happens

**Comment by Memeverze** [comment]
it doesnt start

**Comment by Memeverze** [comment]
> That just means you already have the python packages it is trying to download. If it’s not working, something else is causing the issue.

but the code to start the thing doesnt start, probably idk.

**Comment by XxKingsxX-Pinu** [comment]
run the py file separately with -d and see what it says, you probably dont have correct json formatting

**Comment by Memeverze** [comment]
> run the py file separately with -d and see what it says, you probably dont have correct json formatting

i used https://jsonlint.com/ it says its valid.

**Comment by Memeverze** [comment]
> run the py file separately with -d and see what it says, you probably dont have correct json formatting
How? sorry im new to this stuff.

**Comment by Memeverze** [comment]
wait. forget it 
90% im supposed to rename config_example
