### ISSUE TITLE
Out of Bounds exception

### ISSUE THREAD

**Issue by NFKRZZ** [rdeepak2002/reddit-place-script-2022#26]
currently on line 307, when it tries to do the 3rd iteration or when credentials_index is equal to 2, it crashes and throws an index out of range error. I'm not sure exactly why we are referencing ENV_R_START as it only has 2 values, x initial and y initial?
`current_r = int(json.loads(os.getenv("ENV_R_START"))[credentials_index])`

**Comment by JAKONL** [comment]
Each thread should be given it's own starting point coordinates within your source image. 
 
example:
```
ENV_R_START='["0","5","6","7","9"]'
ENV_C_START='["0","5","6","8","9"]'
```

**Comment by NFKRZZ** [comment]
ahhh wait is ENV_R_START just a list of the various X initial positions that each thread will have and then ENV_C_START is their corresponding y initial values?

**Comment by NFKRZZ** [comment]
> Each thread should be given it's own starting point coordinates within your source image.
> 
> example:
> 
> ```
> ENV_R_START='["0","5","6","7","9"]'
> ENV_C_START='["0","5","6","8","9"]'
> ```

thank you I'm just stupid lol

**Comment by JAKONL** [comment]
If we write out those variables they are: Environment Row Start and Environment Column Start -- I guess it would be more clear if it said something about thread in there (ex. Environment Thread Row Start Array)
