### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TNT599** [rdeepak2002/reddit-place-script-2022#266]
# Bug Report Form

## Checklist

- [* ] I am using the latest version of the code.
- [* ] I am absolutely sure I read the README in its entirety.
- [* ] I have made sure this is not a duplicate issue.
- [* ] I have filled out this form correctly.

## Describe the bug

Just doesn't want to work

## To Reproduce

Steps to trigger the bug:

run main.py

## Expected behavior

Start Bot

## Additional context

![Screenshot 2022-04-03 110811](https://user-images.githubusercontent.com/73024026/161434598-25ed100b-b392-4cf1-b871-08ba1f43dd4a.png)

**Comment by ixi2101** [comment]
That looks like an issue with your config.json

**Comment by TNT599** [comment]
Okay, if I link it could you look at it?

**Comment by TNT599** [comment]
https://file.io/ii6FY16XKY25

**Comment by ixi2101** [comment]
> Okay, if I link it could you look at it?

You can copy and paste it into these comments

**Comment by TNT599** [comment]
{
  "image_path": "image.png",
  "image_start_coords": [ 231, 0 ],
  "thread_delay": 2,
  "unverified_place_frequency": false,
  "proxies": [ "1.1.1.1:8080", "2.2.2.2:1234" ],
  "compact_logging": true,
  "workers": {
    "worker1username": "TalkyRaptor",{
      "password": "blank",
      "start_coords": [ 0, 0 ]
    },
  }
}

**Comment by TNT599** [comment]
My password is not blank, it is just there as a placeholder. When I ran the script, the config had my actual password.

**Comment by ixi2101** [comment]
It should be 
`
"workers": {
		"TalkyRaptor":{
			"password": "blank",
			"start_coords": [ 0, 0 ]
			},
	}
`

**Comment by TNT599** [comment]
k
