### ISSUE TITLE
What am I doing wrong here?

### ISSUE THREAD

**Issue by jdroo** [rdeepak2002/reddit-place-script-2022#274]
Not sure what I'm doing wrong here, set everything out, checked my config file. So I'm a little lost

Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\oof\Desktop\reddit-place-script-2022-main\main.py", line 594, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "C:\Users\oof\Desktop\reddit-place-script-2022-main\main.py", line 408, in get_unset_pixel
    new_rgb = self.closest_color(target_rgb)
  File "C:\Users\oof\Desktop\reddit-place-script-2022-main\main.py", line 106, in closest_color
    if target_rgb[3] != 0:
IndexError: tuple index out of range

**Comment by Risewill23** [comment]
You likely trying to draw is the second half of the board and I don't think thats been added yet

**Comment by jdroo** [comment]
Second half? Pretty sure I'm in the first half

config has

"image_start_coords": [648, 436],

and

"start_coords": [0, 0]

**Comment by Risewill23** [comment]
are you using transparency because transparency can be broken?

**Comment by jdroo** [comment]
using a .jpg

**Comment by Risewill23** [comment]
is it a 1 by 1 image?

**Comment by jdroo** [comment]
7x11

**Comment by Risewill23** [comment]
do you have the image path right in config.json?

**Comment by ixi2101** [comment]
Looks like you are on an older version

**Comment by jdroo** [comment]
let me check

**Comment by jdroo** [comment]
yes, it's correct
 I have the .jpg in the root with the script it's self and the path is 
"image_path": "image.jpg",

**Comment by ixi2101** [comment]
This was fixed in #250 
Can you try on the latest version.

**Comment by Risewill23** [comment]
> using a .jpg

**Comment by jdroo** [comment]
> 

you sure? I mean I can redownload and see. give me a sec.

**Comment by jdroo** [comment]
You Right! Thanx for the help! did not realize it updated lol
