### ISSUE TITLE
How to make non-rectangle shapes

### ISSUE THREAD

**Issue by ItCameFr0mMars** [rdeepak2002/reddit-place-script-2022#276]
Hello, I have some art that I want to build that extends irregularly. How can I build it?

**Comment by Risewill23** [comment]
You would need transparency pixels but I don't think its been correctly added

**Comment by ItCameFr0mMars** [comment]
oh okay. i hope this gets added soon. like a way to ignore transparent pixels

**Comment by ItCameFr0mMars** [comment]
when will transparent pixels be supported to be ignored?
