### ISSUE TITLE
Are you able to compile this into GUI?

### ISSUE THREAD

**Issue by Glass47** [rdeepak2002/reddit-place-script-2022#28]
No need to be fancy shit just option to load specific image what bots should draw and repair if i select that option. Will pay you 10$ :) Also i want support for multiple accounts and perhaps proxies so they don't get banned if they do IP detection. Or if they are not IP detected/shadowbanned then just compile without proxy support. But support for mutliple accounts. :)

**Comment by Randomblock1** [comment]
- I don't know about the other contributors but a GUI seems unnecessary and a lot of work. With this, you just edit the config and paste a JPG. No need for GUI.
- It already has support for multiple accounts, read the README
- Proxy support is possible, that's something I would like too
- This doesn't compile, you just install Python, edit the config file, and go.

**Comment by Glass47** [comment]
Okay. I need to see how this works because i plan to use at least 50 accounts.. Or maybe hundreds, my wish is to create my country flag and defend it 24/7 that nobody can even think about attacking it :) Thank you mate!

**Comment by kallejre** [comment]
I somewhat agree with Glass47 because managing user accounts in lists is slightly inconvenient. Would using CSV file instead of arrays be acceptable? This would mean need for two configuration files.

**Comment by Randomblock1** [comment]
I am planning to move all this into a YAML or JSON file, eventually. For now, you'll just have to deal with it, unfortunately.

**Comment by brandii-co** [comment]
The r/place event will probably only last for 72 hours, given the time we have left it's inessential to focus on a GUI

**Comment by JAKONL** [comment]
Unless someone wants to write a wrapper for this constantly changing code and keep it maintained I do not see this as feasible. @brandii-co called it. Place closes in 72 hours.
