### ISSUE TITLE
[BUG] Calls to https://www.reddit.com fail when account is opted out of "new" reddit redesign 

### ISSUE THREAD

**Issue by seaweeduk** [rdeepak2002/reddit-place-script-2022#285]
# Bug Report Form

## Checklist

- [X] I am using the latest version of the code.
- [X] I am absolutely sure I read the README in its entirety.
- [X] I have made sure this is not a duplicate issue.
- [X] I have filled out this form correctly.

## Describe the bug

Obtaining access token fails, possibly due to opting out of reddit redesign on the account

## To Reproduce

Steps to trigger the bug:

1. Run script

## Additional context

```
2022-04-03 18:18:20.114 | INFO     | __main__:task:543 - Obtaining access token...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 546, in task
    BeautifulSoup(r.content, features="html.parser")
AttributeError: 'NoneType' object has no attribute 'contents'
```

I fixed the error by manually replacing the URL in line 544 with new.reddit.com
`
                    r = client.get("https://new.reddit.com/")`

I am assuming it's because I don't use the new reddit redesign by default on that account so something fails when it goes to https://www.reddit.com

**Comment by Risewill23** [comment]
#286
