### ISSUE TITLE
Anyone can confirm if the only existing ban is a 20 minute ratelimit?

### ISSUE THREAD

**Issue by Trollmo** [rdeepak2002/reddit-place-script-2022#287]
Anyone can confirm if the only existing ban is a 20 minute ratelimit?

If it is true i could just set more accounts and enjoy the bot right?

**Comment by Risewill23** [comment]
I think there is like a year ban

**Comment by AlexX1-dev** [comment]
Nope 138465:33:14 is the ban time

**Comment by thedankeststorm** [comment]
20 minutes ratelimit only happens when you register your account with a crappy VPN / untrustworthy ISP.

**Comment by michaelshumshum** [comment]
> If it is true i could just set more accounts and enjoy the bot right?

some people manage to get hundreds of accounts working at the same time, while people like me get their accounts banned without even touching r/place yet. it's very unclear how the ban works.

**Comment by omar2205** [comment]
Did you verify your email?

**Comment by michaelshumshum** [comment]
> Did you verify your email?

yup. i think the new system is banning accounts based on age now. if they notice tons of accounts accessing from an ip, all with less than 1 week age, i think they are banned. i was observing the american flag takeover just now and i found some 0 karma accounts, most likely bots, that seemed to be functional. the only thing that made them a little different was that they were made at least a month ago.

i guess the only solution would be to buy accounts from other sources. if they do this again, we could hold on to the accounts we have made and use them then.

**Comment by LukachoLombardi** [comment]
Yeah there's a 15 year ban for new accounts

**Comment by omar2205** [comment]
> Yeah there's a 15 year ban for new accounts

Not true, just created 3 accounts, and have 5mins cooldown/px

**Comment by LukachoLombardi** [comment]
not for all of them, but at least for my 16 accounts all sharing the same name prefix lol
