### ISSUE TITLE
[BUG]__main__:task:531 - Failed to connect to websocket

### ISSUE THREAD

**Issue by n-OlegS** [rdeepak2002/reddit-place-script-2022#290]
![image](https://user-images.githubusercontent.com/95242220/161441737-938fdc75-6fc9-4200-ae99-b7d7b9e054f8.png)

**Comment by rdeepak2002** [comment]
Closing this issue since it is a duplicate of https://github.com/rdeepak2002/reddit-place-script-2022/issues/280
