### ISSUE TITLE
Failed to connect to websocket [BUG]

### ISSUE THREAD

**Issue by Enyrox** [rdeepak2002/reddit-place-script-2022#291]
# Bug Report Form

## Checklist

- [ Y ] I am using the latest version of the code.
- [ Y ] I am absolutely sure I read the README in its entirety.
- [ Y ] I have made sure this is not a duplicate issue.
- [ Y ] I have filled out this form correctly.

## Describe the bug

When I launch start.bat, "2022-04-03 20:10:35.519 | ERROR    | __main__:task:531 - Failed to connect to websocket, trying again in 30 seconds..." shows up. I doesn't place pixels

## To Reproduce

Steps to trigger the bug:

1. Go to 'reddit-place-script-2022-main'
2. Click on 'start.bat'
3. See error

## Expected behavior

Works and place pixels

**Comment by Risewill23** [comment]
its likely just a ratelimit

**Comment by OrioPrisco** [comment]
It may be but it works perfectly fine on one machine and I get this error on the error. Seems odd

**Comment by olli-exe** [comment]
It seems like "https://new.reddit.com/login" is down and it cant grab the csrf on line 515 so it throws an error?

![image](https://user-images.githubusercontent.com/70218837/161442373-c877acf7-a98c-4ec7-b814-46c6c535059d.png)
![image](https://user-images.githubusercontent.com/70218837/161442395-269a6aea-7dd5-4219-8977-e9bdb1704835.png)

**Comment by kagenokurei** [comment]
WS connections need to be persistent and stay up as long as possible.

**Comment by thedankeststorm** [comment]
> its likely just a ratelimit

It isn't. Something is up with the API.

**Comment by matbcvo** [comment]
I'm having same problem.

**Comment by maltejur** [comment]
Replacing all `new.reddit.com` with `reddit.com` seems to fix the issue

**Comment by maltejur** [comment]
Probably caused by https://github.com/rdeepak2002/reddit-place-script-2022/pull/286

**Comment by omar2205** [comment]
> Probably caused by #286

year, when I restored before that it worked

**Comment by Enyrox** [comment]
> Probably caused by #286

what is #286?

**Comment by Risewill23** [comment]
#292

**Comment by Risewill23** [comment]
Should work now with the latest update

**Comment by omar2205** [comment]
yeah, I vote close the issue

**Comment by tshrpl** [comment]
now it hangs indefinitely
after printing this line
```console
root@ubuntu-s-1vcpu-1gb-amd-blr1-01:~/reddit-place-script-2022# python3 main.py -d
2022-04-03 18:45:07.493 | INFO     | __main__:load_image:135 - Loaded image size: (32, 9)
```

**Comment by omar2205** [comment]
it worked for me, and placed the pixels accordingly

**Comment by test2a** [comment]
```` 2022-04-04 04:04:54.679 | ERROR    | __main__:task:643 - Failed to connect to websocket, trying again in 30 seconds... ````


 i am getting this error ```` "proxies": [ "98.170.57.231:4145", "174.64.199.82:4145" ], ````

is what i put into my config, i got these socks5 proxies so i am not sure if i need to write socks as prefix to the IP ??

@Risewill23
