### ISSUE TITLE
[BUG] hangs indefinitely

### ISSUE THREAD

**Issue by tshrpl** [rdeepak2002/reddit-place-script-2022#294]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

after the latest commit, the script hangs indefinitely after printiing the following line
```console
root@ubuntu-s-1vcpu-1gb-amd-blr1-01:~/reddit-place-script-2022# python3 main.py -d
2022-04-03 18:45:07.493 | INFO     | __main__:load_image:135 - Loaded image size: (32, 9)
```

config.json:
```json
{
    "image_path": "image.png",
    "image_start_coords": [1290,664],
    "thread_delay": 2,
    "proxies": ["1.1.1.1:8080","2.2.2.2:1234"],
    "unverified_place_frequency": false,

    "workers": {
        "xx": {
            "password": "xx",
            "start_coords": [0, 0]
        }
    }
}
```

**Comment by Risewill23** [comment]
Remove `"proxies": ["1.1.1.1:8080","2.2.2.2:1234"],` they are not real proxies and just examples

**Comment by tshrpl** [comment]
yeah i'm a dumbass
