### ISSUE TITLE
[BUG] json.decoder.JSONDecodeError: Invalid \escape: line 2 column 22 (char 23)

### ISSUE THREAD

**Issue by kiadxn** [rdeepak2002/reddit-place-script-2022#297]
# Bug Report Form

## Checklist

- [ ] I am using the latest version of the code.
- [ ] I am absolutely sure I read the README in its entirety.
- [ ] I have made sure this is not a duplicate issue.
- [ ] I have filled out this form correctly.

## Describe the bug

when i run start.bat i get json.decoder.JSONDecodeError: Invalid \escape: line 2 column 22 (char 23)
## To Reproduce

Steps to trigger the bug:

1. select path
2. run start.bat
3. See error

## Additional context

    "image_path": "C:\Games\Image\pxArt.png",
    "image_start_coords": [724, 726],
    "thread_delay": 2,
    "unverified_place_frequency": false,
    "compact_logging": true,
    "workers": {
        "*****": {
            "password": "*****",
            "start_coords": [0, 0]
        },
        "*****": {
            "password": "*****",
            "start_coords": [0, 0]
        }
    }
}

**Comment by Risewill23** [comment]
`"image_path": "C:\Games\Image\pxArt.png",` to `"image_path": "C:\\Games\\Image\\pxArt.png",`

**Comment by kiadxn** [comment]
> `"image_path": "C:\Games\Image\pxArt.png",` to `"image_path": "C:\\Games\\Image\\pxArt.png",`

thanks once again
