### ISSUE TITLE
What corner's coordiantes should we use in .env?

### ISSUE THREAD

**Issue by ItCameFr0mMars** [rdeepak2002/reddit-place-script-2022#30]
title

**Comment by EntropyValley** [comment]
Top Left

**Comment by JAKONL** [comment]
0,0 is the top left pixel of an image (and the "place" board).

**Comment by Randomblock1** [comment]
Set it to the top left coordinates of the r/place board where you'd like to put it. If you know how big your JPG is, you should be able to line it up accordingly.

For example, if you set a 5x5 image to 100,100, it will draw the top left of the image at 100,100, and the bottom right corner at 105,105.
