### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ELPoupa** [rdeepak2002/reddit-place-script-2022#305]
Hi, I just downloaded the new version of the bot, but I'm not able to use it, every time I try to start I get this error
 
 **File "main.py", line 28
    self.pixel_x_start: int = self.json_data["image_start_coords"][0]
                      ^
SyntaxError: invalid syntax** 

I don't think there are any problems in my config

**{
	"image_path": "image.png",
	"image_start_coords": [120, 120],
	"thread_delay": 2,**

Thanks in advance

**Comment by Risewill23** [comment]
Doesn't look like your using the latest version

**Comment by ELPoupa** [comment]
> Doesn't look like your using the latest version

just tried to download it again, it worked

Thanks
