### ISSUE TITLE
Can I make a GUI out of this?

### ISSUE THREAD

**Issue by vesk4000** [rdeepak2002/reddit-place-script-2022#31]
I would like to make a quick GUI with Godot that can fetch and display the current state of r/place and can draw on it. Can I use this as a sort of backend?

**Comment by Randomblock1** [comment]
We'll need to hear from the owner @rdeepak2002, but this is open-source, and as long as you don't sell it or something, I personally don't see why not. Do wait for the owner, though.

**Comment by Glass47** [comment]
@vesk4000 Do you have discord?

**Comment by vesk4000** [comment]
> @vesk4000 Do you have discord?

I do, it's Vesk#4450

**Comment by jdroo** [comment]
do this plez

**Comment by rdeepak2002** [comment]
Hey, feel free to use this in any project. I made this original repo as a fun exercise and did not expect it to become this popular. 

I would also prefer if you gave credit this original repository (since many people have contributed to the code). 

Good luck with your project!
