### ISSUE TITLE
[BUG] successfully placing but pixels not changing

### ISSUE THREAD

**Issue by kiadxn** [rdeepak2002/reddit-place-script-2022#310]
# Bug Report Form

## Checklist

- [ ] I am using the latest version of the code.
- [ ] I am absolutely sure I read the README in its entirety.
- [ ] I have made sure this is not a duplicate issue.
- [ ] I have filled out this form correctly.

## Describe the bug

when i run start.bat everything works perfectly but the pixels i chose stay the same 

## To Reproduce

Steps to trigger the bug:

1. select path
2. run start.bat
3. authorizes 
4. no change 

## Additional context

{
    "image_path": "C:\\Games\\Image\\pxArt.jpg",
    "image_start_coords": [30, 438],
    "thread_delay": 2,
    "unverified_place_frequency": false,
    "compact_logging": true,
    "workers": {
        "username": {
            "password": "*****",
            "start_coords": [0, 0]
        },
        "username": {
            "password": "*****",
            "start_coords": [0, 0]
        }

**Comment by rdeepak2002** [comment]
Yeah I feel like Reddit's API would return an error message if the pixel was not actually placed.
