### ISSUE TITLE
Verbose Mode Off Issue - Threads Reporting Writing to Same Pixel

### ISSUE THREAD

**Issue by JAKONL** [rdeepak2002/reddit-place-script-2022#32]
Greetings team, 

I have noticed when verbose is off I see all threads reporting they are writing to the same pixel.
Screen shot:
![Screen Shot 2022-04-02 at 12 53 27 AM](https://user-images.githubusercontent.com/16417680/161373111-5b6abe47-f6ec-4d03-a45f-df3ad8e89cdc.png)

When Verbose Mode is turned On the threads all report they are writing to different pixels:
![Screen Shot 2022-04-02 at 12 55 37 AM](https://user-images.githubusercontent.com/16417680/161373134-eb95f881-c686-4a60-ae24-2acfe199a6ff.png)

Unfortunately I am too tired to dig into this at the moment but will get back at it tomorrow. If one of you can figure this out I would greatly appreciate it!

Thanks
JAK

**Comment by Randomblock1** [comment]
Yeah, I noticed that too. It seems like it came in with the map pixel detection, because it seemed to work fine before that.

My best guess is that it returns the same coordinates as long as it seems to be not matching, regardless of which threads calls it. Yet another counter to be added, somewhere...

**Comment by JAKONL** [comment]
Wasn't the verbose switch added after the map pixel detection?

**Comment by Randomblock1** [comment]
Oh yeah, my bad, I misunderstood the issue. That is odd. I'll look into it, but I also don't have much time.

**Comment by Randomblock1** [comment]
OK I have no idea why this is happening, setting delay_between_launches_seconds to like 3 seems to fix it.

My current theory is that without those prints, the program ran _too_ fast and all threads ran at the exact same time or something. I don't think I've fixed the problem but it, uh, _should_ work.

**Comment by Randomblock1** [comment]
Seems to be fixed now, was a combination of verbose mode messing things up and an entirely different issue.
