### ISSUE TITLE
Not a bug or anything. I just don't know why this isn't working for me...sorry to bother..

### ISSUE THREAD

**Issue by Nobrain98** [rdeepak2002/reddit-place-script-2022#33]
Help?

`PS C:\Users\PC\Documents\GitHub\reddit-place-script-2022> & C:/Users/PC/AppData/Local/Programs/Python/Python310/python.exe c:/Users/PC/Documents/GitHub/reddit-place-script-2022/main.py
image size:  (13, 14)
Traceback (most recent call last):
  File "c:\Users\PC\Documents\GitHub\reddit-place-script-2022\main.py", line 494, in <module>
    num_credentials = len(json.loads(os.getenv("ENV_PLACE_USERNAME")))
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType`

**Comment by Randomblock1** [comment]
Your .env file is malformed. Read the README for an example, and copy-paste it, changing the values.

**Comment by Nobrain98** [comment]
does .env need to be names something specific or is it just ".env" example I currently have it named "config.env".

I did copy from the readme and just filled in the fields...

**Comment by EntropyValley** [comment]
it needs to be named .env, no name before the extension
