### ISSUE TITLE
[BUG] Cannot use proxies that require authentication

### ISSUE THREAD

**Issue by aidan-walden** [rdeepak2002/reddit-place-script-2022#333]
# Bug Report Form

## Checklist

- [ x ] I am using the latest version of the code.
- [ x ] I am absolutely sure I read the README in its entirety.
- [ x ] I have made sure this is not a duplicate issue.
- [ x ] I have filled out this form correctly.

## Describe the bug

Trying to use proxies with authentication in config.json, I get "Failed to connect to websocket" error

## To Reproduce

Steps to trigger the bug:

1. Place a proxy in the format "username:password@ip:port" in config.json
2. Run the script

## Expected behavior

The proxy connects.

**Comment by aidan-walden** [comment]
These types of proxies require you to manually append "http://" to the beginning of each URL, as it turns out.

**Comment by gmorningman** [comment]
> These types of proxies require you to manually append "http://" to the beginning of each URL, as it turns out.

what did you mean by this? is it the below?

```
{
	"thread_delay": 2,
	"unverified_place_frequency": false,
	"proxies": ["http://username:password@1.1.1.1:8080", "2.2.2.2:1234"],
	"compact_logging": true
}
```

**Comment by aidan-walden** [comment]
Like the 1st proxy in that array, yes
