### ISSUE TITLE
Transparancy broke for .jpg with RGB(69,42,0).

### ISSUE THREAD

**Issue by thedankeststorm** [rdeepak2002/reddit-place-script-2022#338]
~~Using .png would make the bot place white colors into the transparent pixel.~~
Using .jpg with RGB(69,42,0) would make the bot reports that it's placing "Invalid Color" into the pixel, but instead it uses "burgundy" - the first color of the pallete.

Edit: .png works fine. It was my bad.

**Comment by thedankeststorm** [comment]
Whoops, .png works fine actually. It was my mistake.
.jpg's issue still persists, however.

**Comment by deemfox** [comment]
cant reproduce this on an up to date version of main. tested with a 100x100 jpg of (69,42,0) and it skips all pixels as transparent correctly

**Comment by thedankeststorm** [comment]
> cant reproduce this on an up to date version of main. tested with a 100x100 jpg of (69,42,0) and it skips all pixels as transparent correctly

Weird... well, maybe i'll stick with .png for now. Sorry for the trouble.
