### ISSUE TITLE
Bot placing pixels out of range of image

### ISSUE THREAD

**Issue by EntropyValley** [rdeepak2002/reddit-place-script-2022#34]
I'm not quite sure why, but for some reason my bot accounts are only placing pixels on the coordinate one below what should be the bottom left corner of the image.  I've double checked my image resolution and coordinate placements, but everything appears to be fine in terms of config.  I'm looking into the issue, but figured I'd make others aware.

**Comment by Randomblock1** [comment]
Enable Verbose Mode in the code, and does it print the correct coordinates or do the coordinates not match what it's doing?

**Comment by EntropyValley** [comment]
I think I found the issue.  Inside get_unset_pixel, verbose mode was added to an if statement that has other functionality besides printing – namely, breaking a while loop.  Going to try changing that and seeing if it fixes it.

**Comment by EntropyValley** [comment]
Yep, looks like it's picking correct pixels now. Get_unset_pixel probably needs to be modified to loop back to the top instead of just picking outside of the boundary box tho.

**Comment by EntropyValley** [comment]
Hmm, never mind, looks like it did it again... I think it is a looping issue though

**Comment by funwithtriangles** [comment]
I can confirm this behaviour. Is it just an off-by-one error?

**Comment by EntropyValley** [comment]
No, it's the fact that the pixel checking code just quits if it doesn't find anything by the bottom regardless of if it starts in the middle.  I have a PR inbound that allows it to loop back.  It'll be a minute.

**Comment by EntropyValley** [comment]
See #38

**Comment by EntropyValley** [comment]
Ok, apparently there's still a bug.  I let it run and it appeared to work but now it's acting up again.  Will examine more.

**Comment by EntropyValley** [comment]
Ope, yeah, my fault.  Misread some code and put the wrong values in :sigh:
Will have actually fixed PR in a second.

**Comment by EntropyValley** [comment]
Ok #41 should fix this for real
