### ISSUE TITLE
placing incorrect pixel color

### ISSUE THREAD

**Issue by ItCameFr0mMars** [rdeepak2002/reddit-place-script-2022#35]
I have a purple pixel in the bottom right, but when I run the program, it attempts to place a cyan pixel there. any help?

**Comment by Randomblock1** [comment]
Yeah, it seems like something got broke recently. We'll look into it.

**Comment by ItCameFr0mMars** [comment]
it seems to have some weird offset

**Comment by Randomblock1** [comment]
Try updating and see if it works, some fixes have been made
Also enable Verbose Mode if it still happens

**Comment by Randomblock1** [comment]
Should be fixed
