### ISSUE TITLE
[BUG] no config.json

### ISSUE THREAD

**Issue by razztap** [rdeepak2002/reddit-place-script-2022#353]
im having a trouble 
after start.bat  it says no config.json 
i checked it and renamed it couple times but it still gives same error

**Comment by Risewill23** [comment]
It isn't config_example.json or something right?

**Comment by deemfox** [comment]
you need to create the config.json file. refer to the "Get Started" section of the readme

**Comment by razztap** [comment]
![image](https://user-images.githubusercontent.com/102930014/161453124-cd931693-1047-47ea-af6a-c778c63040f0.png)
 
i have config.json

**Comment by Risewill23** [comment]
Don't you have "Hide extensions for known file types." enabled? that would mean that file is "config.json.json"

**Comment by razztap** [comment]
okay i fixed it thx
