### ISSUE TITLE
[QUESTION] How do I add proxies ?

### ISSUE THREAD

**Issue by MainGoldDragon** [rdeepak2002/reddit-place-script-2022#357]
I finally managed to get this working with minimal instructions and it works fine... for like the 3 throwaway accounts that are not banned/rate limited to 15 years yet. So, apparently it's possible to add proxies, but the way it was instructed didn't work and I get this
![image](https://user-images.githubusercontent.com/36564743/161454148-1e18667a-ec4e-44eb-92bc-d12aa71b981b.png)

**Comment by Risewill23** [comment]
I don't think the websocket is working correctly

**Comment by MainGoldDragon** [comment]
> 



> I don't think the websocket is working correctly

ok so I'm waiting for a fix ?

**Comment by Risewill23** [comment]
I guess so because I get the same thing when I setup it correctly

**Comment by MainGoldDragon** [comment]
k thank you. I hope like another thread said, they make it so we can attach each account a specific proxy
