### ISSUE TITLE
[QUESTION] How do I know if I got rate-limited or banned?

### ISSUE THREAD

**Issue by sdfdger** [rdeepak2002/reddit-place-script-2022#358]
Some of my accounts' timers got put at over 130000 hours and that's technically a rate-limit, the same as the 5 minute ones. Will this tell me if I got banned vs just have a timer?

**Comment by wl1400** [comment]
You need to use proxies or tor, they patched having multiple accounts on the same IP.

**Comment by sdfdger** [comment]
> You need to use proxies or tor, they patched having multiple accounts on the same IP.

All of the accounts I'm using right now didn't have the timer set over 130000, and the ones on [reddit-place-script-2022](https://github.com/rdeepak2002/reddit-place-script-2022) says they're working

**Comment by sdfdger** [comment]
NVM it says if I got banned

| WARNING  | __main__:task:577 - Thread #7 :: CANCELLED :: Rate-Limit Banned
