### ISSUE TITLE
[BUG] Not all traffic goes through proxies

### ISSUE THREAD

**Issue by Prurite** [rdeepak2002/reddit-place-script-2022#373]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

Some traffic (like `r = client.get("https://www.reddit.com/login")`(main.py/473 as time of posting) do not use given proxies.

## To Reproduce

Steps to trigger the bug:
Run the script

## Expected behavior

All traffic goes through given proxies.

## Additional context

In some regions/places, access to reddit is restricted, thus proxies are required.

**Comment by Risewill23** [comment]
I just fixed this in #375

**Comment by Prurite** [comment]
> I just fixed this in #375

Another issue: some leftover `GetProxies` stopping the script from running
