### ISSUE TITLE
[BUG] __main__:task:492 - Failed to connect to websocket, trying again in 30 seconds...

### ISSUE THREAD

**Issue by owengaspard** [rdeepak2002/reddit-place-script-2022#377]
# Bug Report Form

## Checklist

- [Y] I am using the latest version of the code. -- Yes, I am using the one updated minutes ago
- [Y] I am absolutely sure I read the README in its entirety.
- [-] I have made sure this is not a duplicate issue. -- Solutions provided do not work
- [Y] I have filled out this form correctly.

## Describe the bug

Running the bot (start.sh and python3 main.py) return with the error "ERROR    | __main__:task:492 - Failed to connect to websocket, trying again in 30 seconds..."

Log:
`2022-04-04 03:05:18.890 | INFO     | src.utils:load_image:38 - Loaded image size: (655, 50)
2022-04-04 03:05:20.232 | ERROR    | __main__:task:492 - Failed to connect to websocket, trying again in 30 seconds...
2022-04-04 03:05:20.245 | ERROR    | __main__:task:492 - Failed to connect to websocket, trying again in 30 seconds...
2022-04-04 03:05:20.280 | ERROR    | __main__:task:492 - Failed to connect to websocket, trying again in 30 seconds...`

## To Reproduce

Steps to trigger the bug:

1. Run `startverbose.sh`

## Expected behavior

Bot runs and starts to place tiles

**Comment by Risewill23** [comment]
This was fixed is latest update it should work now

**Comment by owengaspard** [comment]
It started to work
