### ISSUE TITLE
[BUG] Failed to connect to websocket

### ISSUE THREAD

**Issue by sdvn** [rdeepak2002/reddit-place-script-2022#378]
# Bug Report Form

## Checklist

- [v ] I am using the latest version of the code.
- [v ] I am absolutely sure I read the README in its entirety.
- [ v] I have made sure this is not a duplicate issue.
- v[ ] I have filled out this form correctly.

## Describe the bug

Requirement already satisfied: certifi==2021.10.8 in c:\python310\lib\site-packages (from -r requirements.txt (line 1)) (2021.10.8)
Requirement already satisfied: charset-normalizer==2.0.12 in c:\python310\lib\site-packages (from -r requirements.txt (line 2)) (2.0.12)
Requirement already satisfied: idna==3.3 in c:\python310\lib\site-packages (from -r requirements.txt (line 3)) (3.3)
Requirement already satisfied: python-dotenv==0.20.0 in c:\python310\lib\site-packages (from -r requirements.txt (line 4)) (0.20.0)
Requirement already satisfied: requests==2.27.1 in c:\python310\lib\site-packages (from -r requirements.txt (line 5)) (2.27.1)
Requirement already satisfied: urllib3==1.26.9 in c:\python310\lib\site-packages (from -r requirements.txt (line 6)) (1.26.9)
Requirement already satisfied: Pillow~=9.1.0 in c:\python310\lib\site-packages (from -r requirements.txt (line 7)) (9.1.0)
Requirement already satisfied: websocket-client~=1.3.2 in c:\python310\lib\site-packages (from -r requirements.txt (line 8)) (1.3.2)
Requirement already satisfied: click==8.1.2 in c:\python310\lib\site-packages (from -r requirements.txt (line 9)) (8.1.2)
Requirement already satisfied: loguru==0.6.0 in c:\python310\lib\site-packages (from -r requirements.txt (line 10)) (0.6.0)
Requirement already satisfied: beautifulsoup4~=4.10.0 in c:\python310\lib\site-packages (from -r requirements.txt (line 11)) (4.10.0)
Requirement already satisfied: stem~=1.8.0 in c:\python310\lib\site-packages (from -r requirements.txt (line 12)) (1.8.0)
Requirement already satisfied: colorama in c:\python310\lib\site-packages (from click==8.1.2->-r requirements.txt (line 9)) (0.4.4)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\python310\lib\site-packages (from loguru==0.6.0->-r requirements.txt (line 10)) (1.1.0)
Requirement already satisfied: soupsieve>1.2 in c:\python310\lib\site-packages (from beautifulsoup4~=4.10.0->-r requirements.txt (line 11)) (2.3.1)
2022-04-04 10:11:23.175 | INFO     | src.utils:load_image:35 - Converted to rgba
2022-04-04 10:11:23.177 | INFO     | src.utils:load_image:38 - Loaded image size: (16, 6)
2022-04-04 10:11:24.960 | ERROR    | __main__:task:492 - Failed to connect to websocket, trying again in 30 seconds...

## To Reproduce

Steps to trigger the bug:

1.After run  start.bat 

## Expected behavior

Replace this text with what _should_ have happened if no bug occurred.

**Comment by Risewill23** [comment]
Update to the latest version this was just fixed

**Comment by sdvn** [comment]
It's Work
