### ISSUE TITLE
Add which proxy is being used to print statements

### ISSUE THREAD

**Issue by NFKRZZ** [rdeepak2002/reddit-place-script-2022#379]
Could we add which proxy is being used to the print statement that gets printed when a pixel is trying to be placed?
![image](https://user-images.githubusercontent.com/43969824/161468222-5a123b82-e6b4-40f6-9055-3867eb894a91.png)

**Comment by Prurite** [comment]
Run main.py with -d option to enable printing debug info including the current proxy used.
```
python main.py -d
```
