### ISSUE TITLE
Fix Code?

### ISSUE THREAD

**Issue by NFKRZZ** [rdeepak2002/reddit-place-script-2022#385]
Got this error
![image](https://user-images.githubusercontent.com/43969824/161471841-c8702bdd-4aed-4e8d-9b9d-716747cb7c47.png)
the init function in proxy.py is calling get_proxies with 1 argument however it needs two
![image](https://user-images.githubusercontent.com/43969824/161471915-755770af-642e-4b7c-a605-b7648676bb22.png)
so I think it should be changed to this
![image](https://user-images.githubusercontent.com/43969824/161471953-86708d8b-7214-4743-8067-e8b67f7c9ed4.png)

**Comment by Edouard127** [comment]
I get a similar one but with `TypeError: get_proxies_text() missing 1 required positional argument: 'self'`

Line 84

**Comment by Edouard127** [comment]
> I get a similar one but with `TypeError: get_proxies_text() missing 1 required positional argument: 'self'`
> 
> Line 84

Line 14 `self.proxies = get_proxies_text()` -> `self.proxies = get_proxies_text(self)` fixes it

**Comment by Risewill23** [comment]
I added that to this pull request #383

**Comment by Skyline-9** [comment]
Fixed in #383
