### ISSUE TITLE
[BUG] Taking wrong colors

### ISSUE THREAD

**Issue by 1101-trash** [rdeepak2002/reddit-place-script-2022#411]
Script works perfectly but it's taking the wrong colors? what could I do? idk to figure it on main.py

**Comment by Maj-ew** [comment]
Same, but instead program "sees" wrong colors and thinks where is actually white it thinks there is red. And I had picture full white so it actually replaces white with white...

**Comment by 1101-trash** [comment]
So what do you suggest? I only have one worker and it keeps placing beige instead of yellow. Maybe swapping some colors in the mappings.py file?

**Comment by Maj-ew** [comment]
I think they fixed it at some point. Download everything again and if starting fresh files won't be enough then change in config thread_delay from 2 to 8 for example

**Comment by 1101-trash** [comment]
I fixed it. At **src/mappings.py** you have to edit the first paragraph. The # color code it's the color that the program will see (at the image), and the number is the color by the # color will be replaced in the canvas.
In example, my image haves at a pixel the color #FFEA73, by default the program will replace it with beige (as in the mapping file). So if I desire that color to be replaced with yellow instead of beige, I just need to replace the # color code at the yellow (number 4 in the canvas) with the one of my image. So if the program sees that the image has that #FFEA73 color pixel, in the canvas will put yellow.
Hope I helped :)
