### ISSUE TITLE
[BUG] Script is unstable

### ISSUE THREAD

**Issue by smith558** [rdeepak2002/reddit-place-script-2022#424]
The script **consistently** crashes after about an hour of runtime. Tested many times. Crashes with `websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.`
![image](https://user-images.githubusercontent.com/44023416/161599810-7bb012e5-7ed0-45f6-9f1f-d6e625e64df0.png)

**Comment by ixi2101** [comment]
Very little development is happening now as the event is nearly over. Your best bet is to roll back to a previous version

**Comment by bolshoytoster** [comment]
@smith558 I think this should work:
```diff
diff --git a/main.py b/main.py
index 9c407c3..55e5490 100755
--- a/main.py
+++ b/main.py
@@ -191,7 +191,11 @@ class PlaceClient:
             )
         )
         while True:
-            msg = ws.recv()
+            try:
+                msg = ws.recv()
+            except websocket._exceptions.WebSocketConnectionClosedException as e:
+                logger.error(e)
+                continue
             if msg is None:
                 logger.error("Reddit failed to acknowledge connection_init")
                 exit()
```
