### ISSUE TITLE
Can someone approve my PR? (r/place is about to end and it has a very important bug fix)

### ISSUE THREAD

**Issue by Risewill23** [rdeepak2002/reddit-place-script-2022#426]
Proxies don't work any all without the bug fix
also its been a day from when I create the PR

**Comment by michaelshumshum** [comment]
i have a feeling r/place might last a little longer. on day 3, they said it would end some time that day. today, they said it would end. i feel like it might go a little longer than we think

**Comment by Risewill23** [comment]
I think that it ends on around the end of the day
