### ISSUE TITLE
FR: Multiple accounts, same client id & secret

### ISSUE THREAD

**Issue by omar2205** [rdeepak2002/reddit-place-script-2022#43]
You can add accounts to the same app and use the app's id and secret.

So, if we have 3 accounts, and one client_id & client_secret, it should try to use them for all the accounts.

**Comment by rdeepak2002** [comment]
Hello, if you repeat the same client secret and client id in the array, then the other accounts will use them.

**Comment by omar2205** [comment]
That's what I did. I'm just suggesting that it's easier if we just used one for all.

**Comment by rdeepak2002** [comment]
Oh I see. Someone can feel free to make a pull request regarding this where if the account array is larger than the secret / client id arrays, then it will use the last value of the secret / client id arrays.

**Comment by Plantchant** [comment]
> That's what I did. I'm just suggesting that it's easier if we just used one for all.

Do we just add the accounts as developers under the personal script?

**Comment by omar2205** [comment]
Yes, if you added them as developer you can use that app's and secret

**Comment by RomainL972** [comment]
One problem is that you can't have more than 20 accounts on one app, so we would have to find a way to make that work with multiple apps ideally

**Comment by thoroc** [comment]
How relevant is this still with the new version?

**Comment by rdeepak2002** [comment]
Since we only require username and password for the latest code, I will be closing this issue.
