### ISSUE TITLE
[BUG] Place frequency not being honored

### ISSUE THREAD

**Issue by EntropyValley** [rdeepak2002/reddit-place-script-2022#45]
# Bug Report Form

## Checklist

- [ Y ] I am using the latest version of the code.
- [ Y ] I am absolutely sure I read the README in its entirety.
- [ Y ] I have made sure this is not a duplicate issue.
- [ Y ] I have filled out this form correctly.

## Describe the bug

Time between places is more than the pixel place frequency.  I'm randomy getting between 400 and 650 seconds between attempts to place instead of 330 like is set in the pixel_place_frequency variable.

## To Reproduce

Run the bot. At least with my setup, I'm getting times upward of 650s/cycle.

## Expected behavior

There should only be 330 seconds between checks.

## Additional context

I've wracked my head over this and can't find out what's wrong.  It's slowing the bot down a ton lmao.

**Comment by Randomblock1** [comment]
It seems like Reddit is throttling you. I have like 6 running just fine. If the code doesn't return an error, it's fetching the refresh times directly from Reddit, so if the timer detection works it works 100%.

Reddit did say they had better protections in place. Not much better, but they are there...

**Comment by EntropyValley** [comment]
Where is the code that does that? I legit can't find that and the web interface shows normal times still, unlike when I saw others get ratelimited by reddit.

**Comment by Randomblock1** [comment]
https://github.com/rdeepak2002/reddit-place-script-2022/blob/073c13f6b303f89b4f961cdbcbd008d0b4437b39/main.py#L155-L169

**Comment by EntropyValley** [comment]
Ah ok.  Yeah, this is unfortunate.  Especially since it's happening right when a flag is expanding over the area I'm trying to hold lol
