### ISSUE TITLE
3 accounts 

### ISSUE THREAD

**Issue by wael9999** [rdeepak2002/reddit-place-script-2022#50]
where should I write the third coordinate?

**Comment by markpaul099** [comment]
I think like this

ENV_R_START='["0", "0", "0"]'
ENV_C_START='["0", "0", "0"]'

**Comment by wael9999** [comment]
no this would add a new x,y coordinate what I want is a new ENV_X_START

**Comment by rdeepak2002** [comment]
ENV_X_START specifies the x and y coordinate of where the image will exist in r/place. ENV_R_START and ENV_C_START will specify where to start drawing from the input image.jpg file.

**Comment by rdeepak2002** [comment]
Closing issue since the code for this and the format for config.json has been updated.
