### ISSUE TITLE
multiple issues

### ISSUE THREAD

**Issue by LuceusW** [rdeepak2002/reddit-place-script-2022#51]
![Capture](https://user-images.githubusercontent.com/102858531/161380375-52cce73e-b1d1-44b5-b48e-70bcdb228b94.PNG)
Timer is 620 seconds instead of 330

![image](https://user-images.githubusercontent.com/102858531/161381211-83a9b36b-7ffb-4d97-878c-f7a54677b04d.png)
Timing is even more messed up with multiple accounts

![image](https://user-images.githubusercontent.com/102858531/161380421-3989ce8d-1c16-4577-b24e-9b48aa784425.png)
![image](https://user-images.githubusercontent.com/102858531/161380432-499bbd18-dbc6-4dd4-97b3-41b1fad8c001.png)
![image](https://user-images.githubusercontent.com/102858531/161380439-53cfc8ac-0d4d-464d-8596-fca5f5a47505.png)
First pixel started at  538,236 instead of 537.236 as stated in .env and all the following pixels seem to be placed in random locations (don't know if it's a bug or if there is a logic behind it)

**Comment by Randomblock1** [comment]
- First issue is Reddit throttling you for some reason or another; the bot timing is accurate
- Second issue is a known problem, having some troubles with the coordinates, working on it

**Comment by LuceusW** [comment]
> * First issue is Reddit throttling you for some reason or another; the bot timing is accurate

what do you mean by bot timing is accurate? It's placing pixels every 10 minutes instead of 5

**Comment by Randomblock1** [comment]
Try now, it should be fixed
