### ISSUE TITLE
why .jpg?

### ISSUE THREAD

**Issue by jdroo** [rdeepak2002/reddit-place-script-2022#52]
why not use .png? so we can use transparency so we can ignore transparent pixels?

**Comment by jdroo** [comment]
oops did not mean to label it as a bug, my bad!

**Comment by thoroc** [comment]
Probably because the owner is more familiar with JPEG handling in Python.

**Comment by Skyline-9** [comment]
I'm sure the owner is familiar with all the image types but just didn't think it was really worth implementing. Support added for more image types in #75, though someone already did a transparency hack with (69, 42, 0)
