### ISSUE TITLE
Can we use the same cliend_id/secret for different accounts?

### ISSUE THREAD

**Issue by AggelosM** [rdeepak2002/reddit-place-script-2022#56]
Or do we have to make a client_id for each account?

**Comment by LuceusW** [comment]
Read instructions and other reported issues before posting please.

It is clearly written:
-If you don't want to create a development app for each account, you can add each username as a developer in the developer app settings. You will need to duplicate the client ID and secret in .env, though.

**Comment by ImNotOnline** [comment]
I just used two alts with 60s stagger and I'm having a ratelimit as well

**Comment by Skyline-9** [comment]
^^ classic read the docs plz

**Comment by Peekofwar** [comment]
What is Client ID though?

**Comment by Skyline-9** [comment]
Client ID and Secret aren't used in the updated version of the script anymore

**Comment by Peekofwar** [comment]
Oh.

**Comment by Skyline-9** [comment]
Check out the README for instructions on running the new version of the script. You can update your local version by running `git pull`. The new version only uses username and password
