### ISSUE TITLE
KeyError: 'access_token'

### ISSUE THREAD

**Issue by rishvidh** [rdeepak2002/reddit-place-script-2022#6]
This is the log I'm getting when I run main.py, what can I do to fix this?

```
available colors (rgb):  [(255, 69, 0), (255, 168, 0), (255, 214, 53), (0, 163, 104), (126, 237, 86), (36, 80, 164), (54, 144, 234), (81, 233, 244), (129, 30, 159), (180, 74, 192), (255, 153, 170), (156, 105, 38), (0, 0, 0), (137, 141, 144), (212, 215, 217), (255, 255, 255)]
image size:  (34, 21)
done drawing image locally to new_image.jpg
330 seconds until next pixel is drawn
refreshing access token...
received response:  {"error": "invalid_grant"}
Traceback (most recent call last):
  File "C:\Users\rishw\Downloads\place_frc\1\main.py", line 189, in <module>
    access_token = response_data["access_token"]
KeyError: 'access_token'
```

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
Make sure you have the right .env variables, it looks like the request is messing up

**Comment by rdeepak2002** [comment]
Hey, I believe this means there was an error when trying to get the access token. Make sure to pull the latest code (we fixed some issues) and ensure that your environment variables are correct. I would suggest printing them out.

**Comment by rishvidh** [comment]
> 

would you happen to know which variables? also which one's the app client ID again?

**Comment by rishvidh** [comment]
> Make sure you have the right .env variables, it looks like the request is messing up

would you happen to know which variables? also which one's the app client ID again?

**Comment by rdeepak2002** [comment]
The client id is the one under "personal use script" and secret is next to "secret". Make sure your app is of type "personal use script" (and not web app).

**Comment by rishvidh** [comment]
@rdeepak2002 and it doesn't matter which redirect URI I use?

**Comment by rdeepak2002** [comment]
I believe the redirect URI does not matter. I used some made up one. Also "invalid_grant" means that there was an authentication issue (so one of your environment variables is incorrect I believe).

**Comment by rdeepak2002** [comment]
These are the steps for retrieving the ENV variables:
1. Visit https://www.reddit.com/prefs/apps
2. Click "create another app" at the bottom
3. Give it any name
4. Select the "script" option
5. Give it any description
6. Give it any about and redirect URLs
7. After creating it, ensure your main account is listed as a developer (you will be providing the username and password for this account)
8. The string next to "secret" is the secret
9. The string under "personal use script" is the client id

**Comment by rdeepak2002** [comment]
Also based on the console output, I believe you are not using the latest version

**Comment by rishvidh** [comment]
@rdeepak2002 I seemed to have fixed this issue but now I have another one

```
Traceback (most recent call last):
  File "main.py", line 264, in <module>
    num_credentials = len(json.loads(os.getenv('ENV_PLACE_USERNAME')))
  File "Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I truncated all the file path btw

**Comment by rdeepak2002** [comment]
There seems to be a JSON parsing error with the username being read from the .env file. 

Is the JSON format of the following line correct in your .env file?:

ENV_PLACE_USERNAME='["rdeepak2002"]'

Note: replace rdeepak2002 with your Reddit username

**Comment by rishvidh** [comment]
@rdeepak2002 everything seems to be working fine now but I get this every 5 mins

```
__________________
Thread #0
Error refreshing tokens or drawing pixel
Trying again in 5 minutes...
__________________

```

does this mean the bot is working?

**Comment by rdeepak2002** [comment]
Oh hm. Is this happening with the latest code? There might be an issue with the token refresh if it is happening every 5 minutes. I will look into this.

**Comment by rishvidh** [comment]
@rdeepak2002 another question, do the image.jpg have to have the same color as the colors available on place?

**Comment by rdeepak2002** [comment]
No, the pixels in the input image can be of any color. I find the closest color to the palette provided by Reddit on line 226 of main.py:

```python
# get converted color
new_rgb = closest_color(target_rgb, rgb_colors_array)
new_rgb_hex = rgb_to_hex(new_rgb)
pixel_color_index = color_map[new_rgb_hex]
```

**Comment by rdeepak2002** [comment]
Closing issue since this specific problem has been resolved.
