### ISSUE TITLE
[BUG] Wasting moves by placing blue on top of blue

### ISSUE THREAD

**Issue by funwithtriangles** [rdeepak2002/reddit-place-script-2022#61]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

I have 6 accounts working on a small area (5x4). Often there is no need for them to make a move because the image is complete, but they still do, by placing the same color on top of itself.

**Comment by funwithtriangles** [comment]
Note: It often seems to be the first pixel of the image

**Comment by TheTallestOfMidgets** [comment]
I have a similar issue, with a quick glance I don't see anywhere in the worker thread code that checks to see if a pixel is already the correct color before placing it ¯\_(ツ)_/¯

**Comment by funwithtriangles** [comment]
This is happening because if it gets through all pixels it just sets pixel 0,0 of the image:

```python
target_rgb = pix[0, 0]
new_rgb = closest_color(target_rgb, rgb_colors_array)
return 0, 0, new_rgb
```

Tried to fix it but didn't have very long!
