### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by Skylancex** [rdeepak2002/reddit-place-script-2022#62]
So basically I run the code and I get this error "ValueError: too many values to unpack (expected 3)" I've probably done something dumb but can anyone help?
Here is the full run module
image size:  (3, 5)
-------Thread #0-------
Refreshing access token...
received new access token:  1680473457874-Y7BF7TnGgKDPVJpBs9MZm5Qe02uhIQ
Getting board
Got image: https://hot-potato.reddit.com/media/canvas-images/1648905786512-0-f-kzZio1q9.png
Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\reddit-place-script-2022-main\main.py", line 492, in task
    current_r, current_c, new_rgb = get_unset_pixel(
  File "D:\reddit-place-script-2022-main\main.py", line 283, in get_unset_pixel
    new_rgb = closest_color(target_rgb, rgb_colors_array)
  File "D:\reddit-place-script-2022-main\main.py", line 111, in closest_color
    r, g, b = target_rgb
ValueError: too many values to unpack (expected 3)

**Comment by ixi2101** [comment]
Can you share the image you are trying to use?

**Comment by Skylancex** [comment]
![image](https://user-images.githubusercontent.com/91775173/161386254-8a5cf893-74b5-489b-9a95-aeaa8813992b.jpg)
It's very basic because it was just a test

**Comment by Skylancex** [comment]
I swapped out my image for the original test image and it now works, how can I create pixel art without it spitting out these errors? I used https://www.pixilart.com to do the original.

**Comment by ixi2101** [comment]
> 
It looks like that website exports as .png or .gif
Currently only .jpg is supported

**Comment by Risewill23** [comment]
Is your image using .jpg?

**Comment by Skylancex** [comment]
Oooh I just renamed the file to .jpg lol I guess I shouldn't have done that

**Comment by rdeepak2002** [comment]
Closing issue since it was due to image format. Also support for png has been recently added I believe.
