### ISSUE TITLE
[BUG] Not working with account using 2FA

### ISSUE THREAD

**Issue by nbourre** [rdeepak2002/reddit-place-script-2022#63]
# Bug Report Form

## Checklist

- [X] I am using the latest version of the code.
- [X] I am absolutely sure I read the README in its entirety.
- [X] I have made sure this is not a duplicate issue.
- [X] I have filled out this form correctly.

## Describe the bug
This script is not working when account uses 2FA.

```
available colors for palette (rgb):  [(255, 69, 0), (255, 168, 0), (255, 214, 53), (0, 163, 104), (126, 237, 86), (36, 80, 164), (54, 144, 234), (81, 233, 244), (129, 30, 159), (180, 74, 192), (255, 153, 170), (156, 105, 38), (0, 0, 0), (137, 141, 144), (212, 215, 217), (255, 255, 255)]
image size:  (2, 2)
-------Thread #0-------
Refreshing access token...
received response:  {"error": "invalid_grant"}
Exception in thread Thread-1:
Traceback (most recent call last):
  File "F:\tools\anaconda3\envs\web_scraping\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "F:\tools\anaconda3\envs\web_scraping\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 461, in task
    access_tokens[credentials_index] = response_data["access_token"]
KeyError: 'access_token'
```

## To Reproduce

Steps to trigger the bug:

1. Execute the script

**Comment by phcreery** [comment]
Getting the same issue here

**Comment by phcreery** [comment]
I resolved it by making sure my `ENV_PLACE_APP_CLIENT_ID` was correct. I originally used my script name, but changing it to the generated Id worked better.

**Comment by itsmohmans** [comment]
It worked for me. I did the following:
go to your 2FA app and get the code, then in "password" field in config.json, write a colon right after your password followed by the 2FA code then save the file and run the script before the timer of the 2FA code runs out.
example of how config.json would be:
``` 
...

    "workers": {
        "workerusername": {
            "password": "YourPasswordHere:123456",
            ...
        }
    }
```
where 123456 is the 2FA code.

**Comment by rdeepak2002** [comment]
Closing issue since a solution has been provided:

> It worked for me. I did the following: go to your 2FA app and get the code, then in "password" field in config.json, write a colon right after your password followed by the 2FA code then save the file and run the script before the timer of the 2FA code runs out. example of how config.json would be:
> 
> ```
> ...
> 
>     "workers": {
>         "workerusername": {
>             "password": "YourPasswordHere:123456",
>             ...
>         }
>     }
> ```
> 
> where 123456 is the 2FA code.
