### ISSUE TITLE
[BUG] List of trace back lines

### ISSUE THREAD

**Issue by TNT599** [rdeepak2002/reddit-place-script-2022#68]
# Bug Report Form

## Checklist

- [*] I am using the latest version of the code.
- [*] I am absolutely sure I read the README in its entirety.
- [*] I have made sure this is not a duplicate issue.
- [*] I have filled out this form correctly.

## Describe the bug

Windows Traceback lines before fail

## To Reproduce

Steps to trigger the bug:

1. run main.py2. 
2. fails at lines: 1009, 946, and 371
## Expected behavior

Continue to complete Thread 1 task

**Comment by ixi2101** [comment]
Can you post the full output?

**Comment by TNT599** [comment]
Yes, I can. It may be a while though.

**Comment by TNT599** [comment]
fixed
