### ISSUE TITLE
Less dumb method of setting pixels

### ISSUE THREAD

**Issue by DeltaNeverUsed** [rdeepak2002/reddit-place-script-2022#7]
You should check out [my fork](https://github.com/DeltaNeverUsed/reddit-place-script-2022), it's an older version of your script, but it has a way to check the pixels on the board.
so that you could implement that in the new version

**Comment by DeltaNeverUsed** [comment]
As well as transparency

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
Try making a pull request, would be easier

**Comment by DeltaNeverUsed** [comment]
It's just such an old version that nothing of it is compatible anymore, so I didn't think it'd be worth it

**Comment by AggelosM** [comment]
Any plans to integrate this method here?

**Comment by DeltaNeverUsed** [comment]
I'm not going to integrate it here myself, but I'm going to continue working on my fork

**Comment by rdeepak2002** [comment]
This is a great suggestion. At the moment I do not have the time to integrate this myself, but anyone can feel free to create a pull request with the update.

**Comment by DeltaNeverUsed** [comment]
Has been merged
