### ISSUE TITLE
Python Dependency Issue

### ISSUE THREAD

**Issue by blueblade747** [rdeepak2002/reddit-place-script-2022#70]
# Bug Report Form

## Checklist

- [yes ] I am using the latest version of the code.
- [yes ] I am absolutely sure I read the README in its entirety.
- [yes ] I have made sure this is not a duplicate issue.
- [ yes] I have filled out this form correctly.

when I run the script it keeps saying this (Linux mint)
![IMG20220402164846](https://user-images.githubusercontent.com/102870336/161391411-8ff7098c-fc06-4fd1-8ac6-fa8c9537e79a.jpg)

**Comment by Risewill23** [comment]
did you run "pip install -r requirements.txt"?

**Comment by CeeJayRed** [comment]
how do you run that?

**Comment by Skyline-9** [comment]
In your terminal, copy and paste
```
pip install -r requirements.txt
```

**Comment by CeeJayRed** [comment]
![image](https://user-images.githubusercontent.com/29681908/161393947-19eb5e69-b5bb-4af1-b360-98eba70e2755.png)
I get this error whenever I do that

**Comment by colingoodman** [comment]
That's the Python shell you have open there. Install `pip3` and run `pip3 install -r requirements.txt`in the same directory as the requirements.txt file. 

https://linuxhint.com/installing_pip_linux_mint/
https://packaging.python.org/en/latest/tutorials/installing-packages/

**Comment by CeeJayRed** [comment]
Thanks I appreciate it I know I kinda hijacked this guy's thread but I saw a reply that related to my question so I just posted it here.  I understand how annoying it must be to try and explain the absolute basics to someone who knows nothing about the language.  Do you know how to install pip3 on windows?

**Comment by Skyline-9** [comment]
`pip3` should come with Python. Looks like you're using windows, so can you open up Powershell and type `python -V`? That will print out the python version if you have it installed.

If it doesn't throw an error, `cd` to your folder and type `pip3 install -r requirements.txt` and `python3 main.py`

**Comment by CeeJayRed** [comment]
![image](https://user-images.githubusercontent.com/29681908/161394433-9ea10ec4-f060-4694-bce8-3eb48f5a8b69.png)
Like so?

**Comment by rdeepak2002** [comment]
Hello, pip is for installing python packages. I would suggest following this guide on how to install pip for windows: https://medium.com/swlh/solved-windows-pip-command-not-found-or-pip-is-not-recognized-as-an-internal-or-external-command-dd34f8b2938f

**Comment by thoroc** [comment]
Could running `python -m pip install -f requirements.txt` works?
