### ISSUE TITLE
Question. how to enter the coordinates correctly

### ISSUE THREAD

**Issue by SileboxUnderfined** [rdeepak2002/reddit-place-script-2022#71]
I have a picture measuring 60 by 20 pixels, but I don't quite understand what coordinates need to be entered into ENV_R_START and ENV_C_START to start drawing a picture from the upper left corner

**Comment by brandii-co** [comment]
With one account:
```
ENV_R_START='["0"]'
ENV_C_START='["0"]'
```

With more accounts:
```
ENV_R_START='["0", "0"]'
ENV_C_START='["0", "1"]'
```

**Comment by Kasax007** [comment]
The bot will automatically move to other spots tho no? Or do you need as many bots as pixels?

**Comment by SileboxUnderfined** [comment]
the problem is that it does not automatically switch to other pixels, and fills the same pixel from different accounts

**Comment by brandii-co** [comment]
> The bot will automatically move to other spots tho no? Or do you need as many bots as pixels?

The bot traverses from the starting pixel to one pixel to the right of it and so on, once it reaches the end of the row it's starting pixel is reset back to the specified starting pixel and moved one column down, so you don't need as many bots as pixels

**Comment by Kasax007** [comment]
Well guess i have to think of a strat then for starting points :D

**Comment by Kasax007** [comment]
It does detect if the color is already correct tho right?

**Comment by brandii-co** [comment]
> the problem is that it does not automatically switch to other pixels, and fills the same pixel from different accounts

> It does detect if the color is already correct tho right?

yea that is a current issue, there is no comparing functionality implemented yet to check for mismatched color pixels

**Comment by Micromanner** [comment]
can someone explain me in more details what these settings do? 
ENV_DRAW_X_START="1"
ENV_DRAW_Y_START="2"

**Comment by SileboxUnderfined** [comment]
![image](https://user-images.githubusercontent.com/20458759/161393616-ccdd2d36-8619-447d-b259-378085da763a.png)
So, i don't understand why :(

**Comment by SileboxUnderfined** [comment]
> can someone explain me in more details what these settings do? ENV_DRAW_X_START="1" ENV_DRAW_Y_START="2"

ENV_DRAW_X_START - x coordinate on place where bot starts its work
ENV_DRAW_Y_START - y coordinate on place where bot starts its work

**Comment by brandii-co** [comment]
> ![image](https://user-images.githubusercontent.com/20458759/161393616-ccdd2d36-8619-447d-b259-378085da763a.png) So, i don't understand why :(

Seems like you ran into the rate limiting issue, check out https://github.com/rdeepak2002/reddit-place-script-2022/issues/19

Also check out the updated repo with the added:
```
ENV_THREAD_DELAY='0'
```
> ENV_THREAD_DELAY Adds a delay between starting a new thread. Can be used to avoid ratelimiting

**Comment by Micromanner** [comment]
x and y coordinate of the canvas? How do I find them out? Sorry if its going off-topic

**Comment by brandii-co** [comment]
> x and y coordinate of the canvas? How do I find them out? Sorry if its going off-topic

When you are on the canvas in r/place:
![image](https://user-images.githubusercontent.com/74169522/161393966-1f20e10f-653c-491c-8507-49ebe9add413.png)
x position: 683
y position: 435

**Comment by Micromanner** [comment]
> > x and y coordinate of the canvas? How do I find them out? Sorry if its going off-topic
> 
> When you are on the canvas in r/place: ![image](https://user-images.githubusercontent.com/74169522/161393966-1f20e10f-653c-491c-8507-49ebe9add413.png) x position: 683 y position: 435

thank you!
