### ISSUE TITLE
Extension of r/place canvas area + new colors

### ISSUE THREAD

**Issue by kinnounko** [rdeepak2002/reddit-place-script-2022#73]
It seems like new colors have been added and the canvas has been made bigger. This causes the following issue:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/reddit-place-script-2022/main.py", line 492, in task
    current_r, current_c, new_rgb = get_unset_pixel(
  File "/home/user/reddit-place-script-2022/main.py", line 284, in get_unset_pixel
    if pix2[x + pixel_x_start, y + pixel_y_start] != new_rgb:
IndexError: image index out of range
```

I think it shouldn't be that hard to fix, but I am low on time right now.

**Comment by viruspro** [comment]
Yup, probably because it got filled so quickly. I'm not sure how to fix it though.

**Comment by JAKONL** [comment]
Looks like the new canvas is returned as a separate image.

I'm seeing the format: timestamp-[0|1]-f-[hash].png for the full images. 

Examples:
Original Grid Image: https://hot-potato.reddit.com/media/canvas-images/1648917722191-0-f-uVR6cAC6.png
Extended Grid Image: https://hot-potato.reddit.com/media/canvas-images/1648917713157-1-f-qwGWTHh0.png

**Comment by firnen0** [comment]
I'm trying to figure out how to add getting the extended area, but idk how to use websocket

**Comment by rdeepak2002** [comment]
mappings.py has all the color mappings. To get the colors provided by Reddit's palette, I used the chrome inspector tools to see which colors they provided and the hex values for them. Feel free to make a pull request regarding this. Notice the "#009EAA" in the screenshot below. 
<img width="1412" alt="Screen Shot 2022-04-02 at 1 11 29 PM" src="https://user-images.githubusercontent.com/7110480/161393735-7b594700-e4db-49b1-b46d-50aa452d1618.png">

**Comment by Nepmia** [comment]
Managed to get the correct area URL when changing the canvas tag to 1 (line 231 in main) (which makes me think that reddit has planned to expand day 1 and that they will probs do it again), tho you will still get an index error if you use the coords gave on reddit, but removing 1000 from a coord from the right canvas won't work either, tried by adding +1000 in `set_pixel_and_check_ratelimit` but still nope, the bot stays sucks on the coord

**Comment by JAKONL** [comment]
We need to send the following request to receive the image:

```
    ws.send(
        json.dumps(
            {
                "id": "3",
                "type": "start",
                "payload": {
                    "variables": {
                        "input": {
                            "channel": {
                                "teamOwner": "AFD2022",
                                "category": "CANVAS",
                                "tag": "1",
                            }
                        }
                    },
                    "extensions": {},
                    "operationName": "replace",
                    "query": "subscription replace($input: SubscribeInput!) {\n  subscribe(input: $input) {\n    id\n    ... on BasicMessage {\n      data {\n        __typename\n        ... on FullFrameMessageData {\n          __typename\n          name\n          timestamp\n        }\n        ... on DiffFrameMessageData {\n          __typename\n          name\n          currentTimestamp\n          previousTimestamp\n        }\n      }\n      __typename\n    }\n    __typename\n  }\n}\n",
                },
            }
        )
    )
```

Then in our web socket parsing loop we need to monitor for the "id" of the response to process both images:

```
    file = ""
    file2 = ""
    while True:
        temp = json.loads(ws.recv())
        if temp["type"] == "data" and temp["id"] == "0":
            msg = temp["payload"]["data"]["subscribe"]
            if msg["data"]["__typename"] == "FullFrameMessageData":
                file = msg["data"]["name"]
        elif temp["type"] == "data" and temp["id"] == "1":
            msg = temp["payload"]["data"]["subscribe"]
            if msg["data"]["__typename"] == "FullFrameMessageData":
                file2 = msg["data"]["name"]
                break
```

I'm thinking at that point it is likely best to combine the images so the coordinate system matches.

**Comment by DeltaNeverUsed** [comment]
i have both canvases working in my fork

**Comment by viruspro** [comment]
> i have both canvases working in my fork
Do you have colors working too?

**Comment by viruspro** [comment]
> i have both canvases working in my fork

Do you have colors working too?

**Comment by DeltaNeverUsed** [comment]
it should work, i haven't tested it though.
haven't pushed that yet, i'm gonna do that now

**Comment by viruspro** [comment]
Ill test it now when its pushed. I'm assuming its on your fork?

**Comment by DeltaNeverUsed** [comment]
yup, and it is pushed

**Comment by viruspro** [comment]
kk ill test it now

**Comment by viruspro** [comment]
![image](https://user-images.githubusercontent.com/12817965/161395323-dffca048-bb96-4ec6-afdd-bb561636de7d.png)
im getting this error one some of the accounts?

**Comment by DeltaNeverUsed** [comment]
the list indices must be integers or slices, not str? or the thing above that's probably not good

**Comment by cubuzz** [comment]
With the most recent changes I'm getting
```
Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\me\Desktop\reddit-place-script-2022\main.py", line 432, in task
    current_r, current_c, new_rgb = get_unset_pixel(
  File "C:\Users\me\Desktop\reddit-place-script-2022\main.py", line 224, in get_unset_pixel
    if pix2[x + pixel_x_start, y + pixel_y_start] != new_rgb:
IndexError: image index out of range
```

**Comment by viruspro** [comment]
im getting rate limits on half the accounts im using?

**Comment by DeltaNeverUsed** [comment]
Are the emails verified?

**Comment by cubuzz** [comment]
Mine are.

**Comment by viruspro** [comment]
they aren't is that why?

**Comment by colingoodman** [comment]
@DeltaNeverUsed Could you open up issues on your repo to take some of this discussion there?

**Comment by Nepmia** [comment]
> they aren't is that why?

Yeah, you must have verified accounts to have 5 min cooldown

**Comment by DeltaNeverUsed** [comment]
@colingoodman 👍

**Comment by smith558** [comment]
this is still an issue, unable to place tiles within the new canvas area

**Comment by ixi2101** [comment]
colours
#95

**Comment by rishvidh** [comment]
is anyone gonna make a pull request to fix this?

**Comment by TNT599** [comment]
Just an idea, and I don't know how to code it exactly. Something like if x>999 switch to second bitmap and subtract 1000?

**Comment by smith558** [comment]
@DeltaNeverUsed has implemented the new area support on his fork, any chance we could merge that? @Randomblock1

**Comment by TNT599** [comment]
> @DeltaNeverUsed has implemented the new canvas area support on his fork, any chance we could merge that? @Randomblock1

Would be hard as his is outdated by over 100 commits but someone can make a new fork and go through their code to try and fix it.

**Comment by DeltaNeverUsed** [comment]
At this point, my fork is completely separate

**Comment by TNT599** [comment]
@DeltaNeverUsed Other then drawing on the extension, is there any more features your fork adds?

**Comment by smith558** [comment]
> > @DeltaNeverUsed has implemented the new canvas area support on his fork, any chance we could merge that? @Randomblock1
> 
> Would be hard as his is outdated by over 100 commits but someone can make a new fork and go through their code to try and fix it.

most of those commits are just README updates however, someone familiar with the code would need to do the merge still tho

**Comment by TNT599** [comment]
A repost to see if my idea would work: 
if x>999 switch to second bitmap and subtract 1000 
We have been able to pull either side of the canvas but not both together as far as I know. This would keep them entirely separate. The only problem is the artwork on both canvases which would have to be run by separate bots in this setup. A fix would be to check each pixels x position and not just the starting one. Could this work?

**Comment by DeltaNeverUsed** [comment]
@TNT599 i've updated the two functions that choose the pixel as well, and transparency actually works, multiple accounts but they don't try to place pixels on a pixel that has already been placed, and some other stuff i don't remember

**Comment by Randomblock1** [comment]
OK, this should be merged into main and work. There's still some stuff that needs to be merged from the fork and I'm 100% certain this will not work when they expand the canvas y-axis, but for now, it's what we have.

Keeping this open until we add y-axis canvas expansion

**Comment by TNT599** [comment]
@DeltaNeverUsed Okay

**Comment by DeltaNeverUsed** [comment]
@Randomblock1 mine is set up so that I just need to change a few things, and it'll work

**Comment by smith558** [comment]
> @Randomblock1 mine is set up so that I just need to change a few things, and it'll work

How's the progress looking? :)

**Comment by rdeepak2002** [comment]
Hello, is this still an issue with the latest code?
