### ISSUE TITLE
Tracebacks

### ISSUE THREAD

**Issue by CL16kai** [rdeepak2002/reddit-place-script-2022#77]
I don't know a lot about python but when I try to run main.py I get these tracebacks:

C:\Users\kaibr\Desktop\reddit-place-script-2022-main>python main.py
[02-Apr-22 19:25:47] :: [INFO] - place-script started
[02-Apr-22 19:25:47] :: [INFO] - Loaded image size: (16, 20)
Traceback (most recent call last):
  File "C:\Users\kaibr\Desktop\reddit-place-script-2022-main\main.py", line 517, in <module>
    num_credentials = len(json.loads(os.getenv("ENV_PLACE_USERNAME")))
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 14 (char 13)

Does anybody know what I've done wrong?

**Comment by Risewill23** [comment]
did you put in the right username and password?

**Comment by CL16kai** [comment]
I've just checked every password again and they're all correct.

**Comment by Risewill23** [comment]
It looks like you have a space or something in the .env

**Comment by rdeepak2002** [comment]
The JSON format for the ENV_PLACE_USERNAME .env variable seems malformed. Please sure your quotation marks are correct and there are no spaces or weird characters.

**Comment by rdeepak2002** [comment]
Closing issue since we are now using a config.json file for configuration rather than .env
