### ISSUE TITLE
can someone please help me I am too stupid for this

### ISSUE THREAD

**Issue by OMFGHelloKitty** [rdeepak2002/reddit-place-script-2022#79]
![image](https://user-images.githubusercontent.com/68202464/161394444-c305f17e-10ad-40aa-b89d-e46f3fbb8e9b.png)
I am getting this error above I can't find what's causing it, please help me. Thanks <3

**Comment by ixi2101** [comment]
I get this error with incorrect credentials in .env

**Comment by rdeepak2002** [comment]
Yes, I believe this is an issue with incorrect credentials provided in the .env file since the response provided by Reddit's authentication system is unable to find the "access_token" object.

**Comment by OMFGHelloKitty** [comment]
oh okay thanks so accounts issue?

**Comment by OMFGHelloKitty** [comment]
sorry I am stupid, thanks
