### ISSUE TITLE
multiple threads don't seem to work

### ISSUE THREAD

**Issue by funwithtriangles** [rdeepak2002/reddit-place-script-2022#8]
Either something wrong with my second account or Reddit is blocking based on IP?

```
__________________
Thread #1
Error refreshing tokens or drawing pixel
Trying again in 5 minutes...
__________________
received response:  {"access_token": "2133296599-IQ6KguD3j7u-aZhWlUjhgb8VUg", "token_type": "bearer", "expires_in": 3600, "scope": "*"}
received new access token:  2133296599-IQ6KguD3j7u-aZhWlUjhgb8VUg
__________________
```

**Comment by MivianTKN** [comment]
I’m getting the same issue, I doubled checked everything.

**Comment by rdeepak2002** [comment]
Hello, thanks for pointing out this issue. I think I should instead store the access_tokens in an array (for each account) since at the moment all the accounts are using a single access_token variable.

**Comment by rdeepak2002** [comment]
I have just pushed a change where access tokens are now stored in an array and associated with each account. I will test this out soon.

**Comment by rdeepak2002** [comment]
I believe it is fixed now. Let me know if it works for you too. Thanks!

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
Error log for a 9x account run:
`available colors for palette (rgb):  [(255, 69, 0), (255, 168, 0), (255, 214, 53), (0, 163, 104), (126, 237, 86), (36, 80, 164), (54, 144, 234), (81, 233, 244), (129, 30, 159), (180, 74, 192), (255, 153, 170), (156, 105, 38), (0, 0, 0), (137, 141, 144), (212, 215, 217), (255, 255, 255)]
image size:  (50, 50)
__________________
Thread #0
__________________
330 seconds until next pixel is drawn
Thread #1
__________________
Thread #2
__________________
__________________
__________________
__________________
330 seconds until next pixel is drawn
Thread #3
__________________
__________________
__________________
Thread #0
__________________
__________________
Thread #8
330 seconds until next pixel is drawn
refreshing access token...
330 seconds until next pixel is drawn
__________________
Thread #5
330 seconds until next pixel is drawn
Thread #7
330 seconds until next pixel is drawn
__________________
330 seconds until next pixel is drawn
__________________
__________________
Thread #3
refreshing access token...
__________________
__________________
__________________
Thread #1
Thread #5
refreshing access token...
Thread #4
refreshing access token...
__________________
__________________
__________________
330 seconds until next pixel is drawn
__________________
__________________
__________________
__________________
Thread #6
Thread #7
__________________
Thread #3
Error refreshing tokens or drawing pixel
Thread #2
refreshing access token...
Thread #0
__________________
Thread #1
330 seconds until next pixel is drawn
__________________
Thread #8
refreshing access token...
Trying again in 5 minutes...
refreshing access token...
Thread #5
Error refreshing tokens or drawing pixel
__________________
Error refreshing tokens or drawing pixel
__________________
Trying again in 5 minutes...
__________________
__________________
Error refreshing tokens or drawing pixel
__________________
Trying again in 5 minutes...
__________________
Thread #7
Error refreshing tokens or drawing pixel
Thread #8
__________________
Trying again in 5 minutes...
__________________
Thread #2
Thread #4
refreshing access token...
Trying again in 5 minutes...
Error refreshing tokens or drawing pixel
Trying again in 5 minutes...
__________________
__________________
Thread #6
Error refreshing tokens or drawing pixel
refreshing access token...
__________________
__________________
Thread #6
Error refreshing tokens or drawing pixel
Trying again in 5 minutes...
__________________
Trying again in 5 minutes...
__________________
__________________
Thread #4
Error refreshing tokens or drawing pixel
Trying again in 5 minutes...
__________________`

**Comment by rdeepak2002** [comment]
Hello, does it work for a smaller number of accounts (like 2?). Also I just pushed a new change where I commented out the try except since it is hiding the exception from appearing.

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
Yes, they all use their own registered apps.

Attempt with 2:
```
available colors for palette (rgb):  [(255, 69, 0), (255, 168, 0), (255, 214, 53), (0, 163, 104), (126, 237, 86), (36, 80, 164), (54, 144, 234), (81, 233, 244), (129, 30, 159), (180, 74, 192), (255, 153, 170), (156, 105, 38), (0, 0, 0), (137, 141, 144), (212, 215, 217), (255, 255, 255)]
image size:  (50, 50)
__________________
Thread #0
330 seconds until next pixel is drawn
__________________
__________________
Thread #0
refreshing access token...
Exception in thread Thread-1 (task):
__________________
Thread #1
330 seconds until next pixel is drawn
__________________
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
__________________
Thread #1
refreshing access token...
Exception in thread Thread-2 (task):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/myuser/Downloads/redditbot/reddit-place-script-2022/main.py", line 189, in task
    secret_key = json.loads(os.getenv('ENV_PLACE_SECRET_KEY'))[credentials_index]
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    self._target(*self._args, **self._kwargs)
    return _default_decoder.decode(s)
  File "/home/myuser/Downloads/redditbot/reddit-place-script-2022/main.py", line 189, in task
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
    secret_key = json.loads(os.getenv('ENV_PLACE_SECRET_KEY'))[credentials_index]
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

**Comment by rdeepak2002** [comment]
Hm there seems to be a JSON parsing error when reading the array environment variable "ENV_PLACE_SECRET_KEY". Could you copy and paste the content of your .env file (with the string contents replaced with "*")?

**Comment by rdeepak2002** [comment]
With 2 accounts, the "ENV_PLACE_USERNAME", "ENV_PLACE_PASSWORD", "ENV_PLACE_APP_CLIENT_ID", "ENV_PLACE_SECRET_KEY", "ENV_R_START", and "ENV_C_START" variables should all be string arrays of size 2.

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
Seems to have been user error, was using single quotations instead of double. I am testing it now and it appears to be working for all 9 accounts, though I got a single ratelimit message for one of them.

**Comment by rdeepak2002** [comment]
I will be closing this issue now since the multithreading is now working. The rate limit issue might be due to the fact that not all accounts have a 5 minute cool down for placing pixels (newer accounts seem to have a higher cool down time). This could also be a result of IP rate limiting.
