### ISSUE TITLE
Extending to match the new board-size

### ISSUE THREAD

**Issue by martan712** [rdeepak2002/reddit-place-script-2022#83]
Hello, when I try to draw at the new available spaces (x in [1000,1999]) I get an error. As far as I can see this is because the image it loads still is only 1000x1000. Is there any way to fix this?

**Comment by Risewill23** [comment]
That's already trying to be added in #73

**Comment by rdeepak2002** [comment]
Closing issue since this is a duplicate already mentioned in https://github.com/rdeepak2002/reddit-place-script-2022/issues/73

**Comment by martan712** [comment]
My bad
