### ISSUE TITLE
Not a bug, just a github noob. How do I do this

### ISSUE THREAD

**Issue by burnermoment8765** [rdeepak2002/reddit-place-script-2022#84]
I feel akward asking for help on this but I literally have barely any knowledge on how to use github. Python 3 is installed but when I put "pip3 install -r requirements.txt" into powershell it just says:

> "pip3 : The term 'pip3' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
> the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + pip3 install -r requirements.txt
> + ~~~~
>     + CategoryInfo          : ObjectNotFound: (pip3:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException"

Is there unspoken code I'm supposed to put in beforehand you're supposed to just know? Am I putting it in the wrong spot? Also I don't know how to just 'create a file' for the .env step. Again, sorry, I'm just an idiot who needs some guidance

**Comment by Risewill23** [comment]
use "pip" for windows
and "pip3" for linux I think

**Comment by burnermoment8765** [comment]
> 

Thanks for the reply, just tried it, but same error. Am I missing a beforehand step?

**Comment by rdeepak2002** [comment]
Try doing:

```shell
pip install -r requirements.txt
```

Also you have to create a file in the project folder with the name ".env" (https://www.wikihow.com/Create-a-Computer-File).

**Comment by Risewill23** [comment]
Did you install python?

**Comment by rdeepak2002** [comment]
Also if pip or pip3 are not working, you have to download Python from here: https://www.python.org/downloads/

If it still does not work, you will have to add Python to path: https://datatofish.com/add-python-to-windows-path/

I would also suggest following this if pip still does not work: https://medium.com/swlh/solved-windows-pip-command-not-found-or-pip-is-not-recognized-as-an-internal-or-external-command-dd34f8b2938f

**Comment by burnermoment8765** [comment]
Hi, yes I have it installed and I made a path and it's still not working, I'm going to try uninstalling and installing python again as it's still not working and see if that works

**Comment by ixi2101** [comment]
Try
`python -m pip install -r requirements.txt`

**Comment by burnermoment8765** [comment]
Hello, that one seemed to almost fix it, as instead I just got a "ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'" message. The file is downloaded though and on my desktop. Should it be moved to be somewhere in the same folder as the python?

**Comment by abhijithsundr** [comment]
You're supposed to run the command in the directory of the requirements.txt file

**Comment by burnermoment8765** [comment]
Again I apologize for my incredible level of tech noob but how do I do that ^^'

**Comment by abhijithsundr** [comment]
In Powershell, use the cd command to navigate to the the directory containing the text file and run your command from there.

**Comment by Skyline-9** [comment]
Find the path of the folder using this: https://www.laptopmag.com/articles/show-full-folder-path-file-explorer. Then, open powershell, type `cd` and paste in the path. After entering that command, you should see the `C:\` part on the left change to your path. That means you are in the correct directory.

Once you are there, type `pip install -r requirements.txt` and `python main.py`

**Comment by esthrshi** [comment]
If you're on Windows, you can also just go to the directory (folder), then type 'cmd' in the search bar. It will open the terminal in that directory

**Comment by burnermoment8765** [comment]
> Find the path of the folder using this: https://www.laptopmag.com/articles/show-full-folder-path-file-explorer. Then, open powershell, type `cd` and paste in the path. After entering that command, you should see the `C:\` part on the left change to your path. That means you are in the correct directory.
> 
> Once you are there, type `pip install -r requirements.txt` and `python main.py`

Thanks so much! The first command worked but `pip install -r python main.py` and `pip install python main.py` (in case I had misunderstood the format) gave me an error message, then I tried doing `cd [python path]` before entering the same codes and still an error. What am I missing?

**Comment by burnermoment8765** [comment]
Thanks for the help guys, I do have another question though. How would the .env file's code work for the multiple developers of one app route rather than making an app for each account? Would I still just do the array list of usernames/passwords?

**Comment by rdeepak2002** [comment]
For multiple developers of one app, you can repeat the app’s secret and client id in the array in the .env

**Comment by burnermoment8765** [comment]
Alright, thank you. My last two questions are the start integers are for the top left corner, yes? and What do env_r_start and env_c_start need to be set to? What do they do?

**Comment by esthrshi** [comment]
> Alright, thank you. My last two questions are the start integers are for the top left corner, yes? and What do env_r_start and env_c_start need to be set to? What do they do?

You're still on an older version of the repo. You need to fetch again to update it to the newest version. The `.env` file has changed to `config_example.json`

**Comment by burnermoment8765** [comment]
oh okay, just updated. Thanks for all the help
