### ISSUE TITLE
API decided to report BS times to the bots

### ISSUE THREAD

**Issue by ShaddowWolf-MC** [rdeepak2002/reddit-place-script-2022#85]
Newest update and the time that is displayed by the script has nothing to do with the real cooldown time.
Tells me i have to wayt 15 Jears via the script but if I sighn is, i can place a tile. any idear why?
thanky you in advance

**Comment by viruspro** [comment]
same problem

**Comment by dbio** [comment]
I see 20 minutes cooldown for some users

**Comment by abhijithsundr** [comment]
Are you using unverified accounts? if you are have you set  `ENV_UNVERIFIED_PLACE_FREQUENCY='True` in the env file?

**Comment by Mnemotechnician** [comment]
same here, after i attempted to use the script for like 10 minutes all the threads began to report a 500,000,000 sec. cooldown

**Comment by Randomblock1** [comment]
Enable Verbose mode, what time number does it give you?

**Comment by Smileynator** [comment]
I am using only 3 accounts, and i am seeing no issues so far. Maybe this is only happening with reasonably sized amount of users on 1 IP?

**Comment by Mnemotechnician** [comment]
this happened to me when i increased the number of accounts from 3 to 6... yeah, i guess, it's an autoban

**Comment by strau0106** [comment]
same thing here, manually restarting every 5 mins

**Comment by Randomblock1** [comment]
Try updating the script, it might be fixed now

**Comment by rdeepak2002** [comment]
Hello, I believe this is fixed with the latest script. I will be closing the issue now.
