### ISSUE TITLE
TRANSPARENT PIXELS BUG

### ISSUE THREAD

**Issue by Covkie** [rdeepak2002/reddit-place-script-2022#87]
# Bug Report Form

## Checklist

- [✅] I am using the latest version of the code.
- [✅ ] I am absolutely sure I read the README in its entirety.
- [✅ ] I have made sure this is not a duplicate issue.
- [✅ ] I have filled out this form correctly.

## Describe the bug

when using transparent pixels/the brown colour, the script places the starting colour then starts drawing a black line to the right

## To Reproduce

Steps to trigger the bug:

use a png or brown colour

## Expected behavior

not do this and ignore the transparent pixels

**Comment by Risewill23** [comment]
Already trying to work on it
