### ISSUE TITLE
I cant get it to run

### ISSUE THREAD

**Issue by Mason-kranz** [rdeepak2002/reddit-place-script-2022#92]
[02-Apr-22 14:43:35] :: [INFO] - place-script started
No valid image path found!
is what I keep seeing, 
The image is uploaded as a PNG , the .env file is done correctly (I think), all the pip stuff is installed. Im lost on how to fix this. Also how does it know what size the image is? like if im trying to upkeep a current image on /place for example

**Comment by 12932** [comment]
it needs to be called image.jpg and it needs to be .jpg and it knows the size bcoz its smart

**Comment by noyza2132** [comment]
is the image file named image.png?

**Comment by Mason-kranz** [comment]
It wasnt, I renamed it and stopped getting the error. Now im not getting any errors but it doesnt seem like anything is happening at all. Each time I try to run it nothing happens/appears

**Comment by esthrshi** [comment]
> It wasnt, I renamed it and stopped getting the error. Now im not getting any errors but it doesnt seem like anything is happening at all. Each time I try to run it nothing happens/appears

Are you getting an error when you run `python3 main.py`?

**Comment by Mason-kranz** [comment]
> > It wasnt, I renamed it and stopped getting the error. Now im not getting any errors but it doesnt seem like anything is happening at all. Each time I try to run it nothing happens/appears
> 
> Are you getting an error when you run `python3 main.py`?
If i copy and paste that into the terminal i get:
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases

but I have python 3, ive been running main.py by going through directory to the file (idk if thats the right term). When i did it that way it would "run" (it would run it and give me errors until i fixed it, not it doesnt seem to run)

I also tried the idle compiler just to see if id get an error msg and It would run in there too and give no errors but it wouldnt do anything.

**Comment by esthrshi** [comment]
> > > It wasnt, I renamed it and stopped getting the error. Now im not getting any errors but it doesnt seem like anything is happening at all. Each time I try to run it nothing happens/appears
> > 
> > 
> > Are you getting an error when you run `python3 main.py`?
> > If i copy and paste that into the terminal i get:
> > Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases
> 
> but I have python 3, ive been running main.py by going through directory to the file (idk if thats the right term). When i did it that way it would "run" (it would run it and give me errors until i fixed it, not it doesnt seem to run)
> 
> I also tried the idle compiler just to see if id get an error msg and It would run in there too and give no errors but it wouldnt do anything.

That's probably because it isn't in your path yet, maybe try this? https://datatofish.com/add-python-to-windows-path/ 
and then restart your computer to be sure.

**Comment by JAKONL** [comment]
Closing stale issue
