### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by noyza2132** [rdeepak2002/reddit-place-script-2022#93]
i cant get it to start. when i run it it gets the board image and then says this:
```
[INFO] - Received board image: https://hot-potato.reddit.com/media/canvas-images/1648925526247-0-f-1CpMuJKu.png
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 435, in task
    current_c,
  File "main.py", line 224, in get_unset_pixel
    if pix2[x + pixel_x_start, y + pixel_y_start] != new_rgb:
IndexError: image index out of range
```

**Comment by 22tooty2** [comment]
also getting this error

**Comment by xcaliber178** [comment]
Are you on the latest version of Python?

**Comment by noyza2132** [comment]
nah 3.7.2 is that the reason?

**Comment by xcaliber178** [comment]
Not positive, but the readme does say to use the latest, and I am on 3.10. I would update to the latest version and see if it helps.

**Comment by Charlie-Henry** [comment]
Looks like the script does not support the new half of the board. The board `.png` file from reddit is only the left side?

**Comment by shadi-hammad** [comment]
Yes, I've only gotten this error when attempting to run the script on the new section of the board. Works otherwise

**Comment by branmart** [comment]
How can we edit it to extend into the new portion of the canvas?

**Comment by noyza2132** [comment]
i just updated, still shows the same error.

**Comment by esthrshi** [comment]
It doesn't work for the new canvas yet. Wait for it to be updated.

**Comment by kittycat959** [comment]
To fix this issue go to the config .json and subtract 1000 from the image_start_coords's x vlaue then in main.py on line 227 change "tag": "0", to "tag": "1", then it will work

**Comment by JoshTPro** [comment]
> 

Did all the steps. Still getting ` image index out of range`
![image](https://user-images.githubusercontent.com/98763067/161399250-d8ea53ea-6991-44c4-9c7d-5729b22d2e48.png)
![image](https://user-images.githubusercontent.com/98763067/161399290-480b7d70-6587-4b62-9dfc-6ef55bf00542.png)
![image](https://user-images.githubusercontent.com/98763067/161399299-d4b08c3e-78b5-4bd8-a1e4-5599a888410c.png)

**Comment by kittycat959** [comment]
> > 
> 
> Did all the steps. Still getting ` image index out of range` ![image](https://user-images.githubusercontent.com/98763067/161399250-d8ea53ea-6991-44c4-9c7d-5729b22d2e48.png) ![image](https://user-images.githubusercontent.com/98763067/161399290-480b7d70-6587-4b62-9dfc-6ef55bf00542.png) ![image](https://user-images.githubusercontent.com/98763067/161399299-d4b08c3e-78b5-4bd8-a1e4-5599a888410c.png)

Make start coords 0,0

**Comment by JoshTPro** [comment]
`File "D:\Coding\reddit-place-script-2022\main.py", line 73, in closest_color
    r, g, b = target_rgb
TypeError: cannot unpack non-iterable int object`

**Comment by nbourre** [comment]
Getting `image index out of range error`.

```
  "image_start_coords": [215, 517],
  ...
    "start_coords": [0, 0]
  ...
```

**Comment by rdeepak2002** [comment]
Hello, is this issue present with the latest code?

**Comment by nbourre** [comment]
> Hello, is this issue present with the latest code? 

It seems to have been fixed. My workers have been helping Canada for the last 30 minutes without problem.

**Comment by rdeepak2002** [comment]
Thanks for the response. Closing issue.
